### ISSUE TITLE
Very Dark Model with 0.9.8 update

### ISSUE THREAD

**Issue by jjmuriel** [adizanni/floor3d-card#10]
With the new update the 3D floor plan is displayed very dark:

<img width="1439" alt="Screen Shot 2021-06-18 at 14 18 04" src="https://user-images.githubusercontent.com/17131600/122607346-08db3480-d040-11eb-8fc9-1d2008ea418c.png">

**Comment by adizanni** [comment]
Hello jjmuriel, please set a value for globalLightPower (between 0 and 1), I have introduced a bug which is not setting the default value when the confiuration value is not set

**Comment by jjmuriel** [comment]
Thank you @adizanni . With a value of 0.5 is fine now.

**Comment by adizanni** [comment]
I need to correct to have a defaiult to 0.5, which was the case beforehand

**Comment by adizanni** [comment]
Issue corrected in v0.9.9
