### ISSUE TITLE
Problems to get object_id

### ISSUE THREAD

**Issue by felipebraz** [adizanni/floor3d-card#100]
**Checklist:**

- [X ] I updated to the latest version available
- [ X] I cleared the cache of my browser

**Release with the issue: 1.4.1-hf2

**Last working release (if known): Nop

**Browser and Operating System: Windows 11 Pro and Google Chrome 100.0.4896.88

**Description of problem:**

A few days ago I was using just fine this incredible card, but today it just stated not to answering my clicks on unsigned (objects that are not on entities list, maybe it's a wrong way to call sorry...) objects. Usually it should show me the object_id, but with no apparent reason just stoped answering my commands.

The click commands appears to be working on signed objects

![image](https://user-images.githubusercontent.com/14303499/163913145-bc4f5d8e-8aa9-4e29-a7e9-b39ec899a1c8.png)

When I click on my A/C it answer my with more-info, as it should.
But when I click on this window

![image](https://user-images.githubusercontent.com/14303499/163913354-948e43e8-137b-4474-b0af-c91fb93e2e2a.png)

nothing happens.

In fact I really don't need this click on unsigned objects, I just need to know the object_id to add on entities list and "use it". If there is another (even better way) works just fine for me.

**Javascript errors shown in the web inspector (if applicable):**

```
No errors on js.
```

![image](https://user-images.githubusercontent.com/14303499/163914084-0240ac37-6f25-45f5-83e6-dc6004be8987.png)

**Additional information:**

My config:

  - theme: Backend-selected
    title: Teste Casa 3d
    path: teste-casa-3d
    type: panel
    badges: []
    cards:
      - type: custom:floor3d-card
        name: Teste 3d
        path: /local/escritorio/
        objfile: Casa_3d.obj
        mtlfile: Casa_3d.mtl
        backgroundColor: '#aaaaaa'
        header: 'yes'
        globalLightPower: 0.3
        shadow: 'yes'
        extralightmode: 'no'
        overlay: 'yes'
        overlay_bgcolor: transparent
        click: 'yes'
        lock_camera: 'no'
        show_axes: 'no'
        sky: 'yes'
        north:
          x: 0
          z: 1
        entities:
          - entity: switch.sonoff_1000f7cb6d_1
            object_id: PolyMesh_1_2_2_362
            type3d: light
            light:
              lumens: 800
          - entity: switch.sonoff_1000f7cb6d_2
            object_id: <dicroicas>
            type3d: light
            light:
              lumens: 400
          - entity: sensor.a4c1380c9d3a_temperature
            object_id: <paredes>
            type3d: color
            colorcondition:
              - color: red
                state: hot
              - color: green
                state: ok
              - color: blue
                state: cool
            entity_template: >-
              [[[ if ($entity < 26) { "cool" } else if ($entity < 28) { "ok" }
              else { "hot" } ]]]
            action: more-info
          - entity: sensor.consumo_corrente_escritorio
            object_id: room_14_80
            type3d: color
            colorcondition:
              - color: red
                state: rensga
              - color: yellow
                state: ok
            entity_template: >-
              [[[ if ($entity < 50) { "debobs" } else if ($entity < 400) { "ok"
              } else { "rensga" } ]]]
            action: more-info
          - entity: sensor.consumo_atual_medidor_do_ar_condicionado_do_escritorio
            object_id: '1_333'
            type3d: color
            colorcondition:
              - color: red
                state: megaConsumption
              - color: yellow
                state: okConsumption
            entity_template: >-
              [[[ if ($entity < 8) { "noConsumption" } else if ($entity < 200) {
              "okConsumption" } else { "megaConsumption" } ]]]
            action: more-info
        object_groups:
          - object_group: dicroicas
            objects:
              - object_id: Circle003_1_334
              - object_id: Circle003_1_341
              - object_id: Circle003_1_348
              - object_id: Circle003_1_355
          - object_group: paredes
            objects:
              - object_id: wall_6_35
              - object_id: wall_7_41
              - object_id: wall_9_53
              - object_id: wall_8_47
              - object_id: wall_1_5
              - object_id: wall_2_11
              - object_id: wall_3_17

**Comment by adizanni** [comment]
Hello @felipebraz , I see that some of your entities do not have an object associated ex:

```yaml
entity: switch.sonoff_1000f7cb6d_2
  object_id:  <----- you need to put a valid object id here
```

with click = 'yes', you tell to the card to ignore the double click, so all actions will be triggered by the simple click event.

The object_id appears in the pop-up only when you are in edit mode. When you are not in edit mode, the click on the object, will do what you have specified in action. If action is empty the default action is to do nothing for all type of entity except for lights (it toggles the associated light) or gesture (it executes the gesture service).

I'm not sure it is clear, it is true that along the evolution of the card I wanted to do changes that would not disrupt the config of the users, but doing this I made some design choices that are not always intuitive. I'm planning to fix this when I will have more time in the release 2.0.

**Comment by adizanni** [comment]
Hello @felipebraz , can you please verify if my explanations help you or you confirm this is a bug

**Comment by felipebraz** [comment]
Hi, sorry for not answering. I had a really crazy week.
Yes, your explanation solved all my issues, thank you very much and I'm sorry for the confusion. There is no bug.
