### ISSUE TITLE
Uncaught Error

### ISSUE THREAD

**Issue by xfyisheng** [adizanni/floor3d-card#102]
Logger: frontend.js.latest.202204050
Source: components/system_log/__init__.py:190
First occurred: 23:16:56 (11 occurrences)
Last logged: 23:20:52
http://192.168.2.2:8123/local/floor3d-card.js?ver=14555:2262:31468 Uncaught Error

**Comment by xfyisheng** [comment]
> @xfyisheng，我需要更多信息，至少是卡的配置，如果需要，还需要模型文件。
I installed it for the first time, and operated according to your YouTube video to prompt this error

**Comment by adizanni** [comment]
Hello @xfyisheng, if you have used the sample, and you have changed the model parameters to point to your home model, you also need to remove the sample entities and sample object groups that are defined, otherwise the card will show and error.
In order for me to be sure if your config is valid, please click on show code editor and cut and paste the config:

![image](https://user-images.githubusercontent.com/35622920/165514630-1800cd8b-4689-4da8-b1d1-a5c88b4cd24a.png)

![image](https://user-images.githubusercontent.com/35622920/165514781-2d5aa19d-8d43-4070-8399-1c9c4c4474ee.png)

**Comment by xfyisheng** [comment]
Thank you. It can already be displayed. Why are the mobile phone and tablet loaded repeatedly?

**Comment by xfyisheng** [comment]
type: custom:floor3d-card
path: /local/ddd
name: Home
objfile: home1.obj
shadow: 'yes'
globalLightPower: '0.8'
object_groups: []
entities: []
zoom_areas: []
mtlfile: home1.mtl
camera_position:
  x: -1171.6987815558477
  'y': 2769.824188535175
  z: 438.1696676705225
camera_rotate:
  x: -1.3837374844264232
  'y': -0.40762130251596834
  z: -1.1253556190702088
camera_target:
  x: 37.36890424945437
  'y': 18.64464320782064
  z: -82.55051697031719

**Comment by adizanni** [comment]
So you are saying that now it is working on your PC ? Good. 
Normally in the mobile, the behaviour should be the same, but if you have an old tablet or smartphone there may be some issues of resources (memory and CPU). I have never seen it being loaded repeatedly.....

**Comment by xfyisheng** [comment]
> 所以你是说现在它在你的电脑上工作？好。通常在移动设备中，行为应该是相同的，但是如果您有旧的平板电脑或智能手机，则可能存在一些资源问题（内存和CPU）。我从来没有见过它被反复加载.....

Logger: frontend.js.latest.202204050
Source: components/system_log/__init__.py:190
First occurred: 21:24:21 (1 occurrences)
Last logged: 21:24:21

http://192.168.2.2:8123/frontend_latest/app.b39ee8d3.js:850:203613 Error: Failed to execute 'define' on 'CustomElementRegistry': the name "floor3d-formfield" has already been used with this registry

**Comment by xfyisheng** [comment]
What about this?

**Comment by xfyisheng** [comment]
This problem occurs after customizing the display area. It's OK after deletion

**Comment by xfyisheng** [comment]
camera_position: { x: -1926.0908137449642, y: 2127.205160436416, z: 223.7797000082715 }
camera_rotate: { x: -1.4265263575361962, y: -0.7445732847984672, z: -1.359608656362665 }
camera_target: { x: 37.36890424945437, y: 18.64464320782064, z: -82.55051697031719 }

After customization, there will be problems with the mobile phone and tablet. By default, the display on the mobile phone and tablet is normal!

**Comment by adizanni** [comment]
Which version of the card you have ? The floor3d-formfield problem was fixed a few releases ago.
The camera settings should work seamlessly on the mobile apps too. Let me check.....

**Comment by xfyisheng** [comment]
![image](https://user-images.githubusercontent.com/39881857/165538285-890f8ed4-4290-4cfc-80b7-5209091a2780.png)
In this way, all devices are normal，This is the default configuration
![image](https://user-images.githubusercontent.com/39881857/165538470-2c37250c-68ac-42e5-9f51-ed801b2b3589.png)
In this way, the computer is normal, but the mobile phone and tablet are not

**Comment by adizanni** [comment]
Please, remove the object_groups, those are only from the sample. It is not causing any issue but it is better to have a clean config. What exactly happens in the mobile view ?

**Comment by xfyisheng** [comment]
The memory and CPU of my iPhone 11 are caused!! Resource issues

**Comment by xfyisheng** [comment]
81.4 MB

**Comment by adizanni** [comment]
It is big but an iPhone 11 should be able to handle it! I need to do some test on my side, if you are willing to share your model

**Comment by xfyisheng** [comment]
OK

**Comment by xfyisheng** [comment]
your email

**Comment by adizanni** [comment]
It is in my profile

**Comment by adizanni** [comment]
I confirm, there is something wrong about the model. I can reproduce the loading loop. On the other hand, the model is big but not huge so it is not clear to me why you have that behavior. Try to send me your sh3d file too for me to see if there are some heavy objects that you can simplify or reduce.

**Comment by xfyisheng** [comment]
Try to change the direction of the mold, and then try if there is any problem with loading. Well, hello, can you email me your teaching video? I'm in China, and sometimes it's inconvenient to watch your videos.

**Comment by adizanni** [comment]
The behavior in the mobile is really due to your model, I've tested other model (big and small) and I could not reproduce what is happening in your model

**Comment by xfyisheng** [comment]
Please take a look at the email address sent to you of the sh3d file. Send it to me after modification. Thank you.

**Comment by xfyisheng** [comment]
The error prompts that the video has been recorded, you look at the mailbox

**Comment by adizanni** [comment]
Ok I have seen your video! I was able to reproduce the issue also on my mobile (iPhone SE) on another big model. Changing the camera parameter did not bring any benefit. I'm now exploring your model. First, try to remove all textures (the picture in posters and paintings). Also replace your beds with curvy pillows with more classic beds. Test the light model first and then you add complex object one by one to see the impact on performances and memory (especially in smartphone). Of course the resources of THREE.js (the library behind the card) are not unlimited, so the model may start to show some problem if it is too big.

**Comment by adizanni** [comment]
The new model you sent me loads ok also on iPhone SE

**Comment by xfyisheng** [comment]
core-2022.4.0
Home Assistant Container

I installed this version. Is it a version problem?

**Comment by xfyisheng** [comment]
Docker

**Comment by adizanni** [comment]
The version could explain the problem you had before:

> http://192.168.2.2:8123/frontend_latest/app.b39ee8d3.js:850:203613 Error: Failed to execute 'define' on 'CustomElementRegistry': the name "floor3d-formfield" has already been used with this registry

Of course it is a best practice to upgrade to the latest version maybe waiting for the Year.Month.X where X > 1.

Your new model is big but it loads regularly on an iPhone SE. It should work now on your iPhone 11 too.

**Comment by xfyisheng** [comment]
![image](https://user-images.githubusercontent.com/39881857/166103983-964e841a-c1d6-42b3-9685-8facdfbed266.png)
Thank you. The problem has been solved. How to add MP4 as the background? And add weather effects

**Comment by xfyisheng** [comment]
![image](https://user-images.githubusercontent.com/39881857/166103983-964e841a-c1d6-42b3-9685-8facdfbed266.png)
Thank you. The problem has been solved. How to add MP4 as the background? And add weather effects

**Comment by adizanni** [comment]
This is a suggestion for an enhancement, it is not possible so far, if you have an idea and you are a javascript programmer, do not hesitate to perform pulls!!

**Comment by xfyisheng** [comment]
I'm not a programmer. I hope to enhance.
