### ISSUE TITLE
object_id Can I fill in more than one at the same time?

### ISSUE THREAD

**Issue by Chen2022** [adizanni/floor3d-card#103]
Can I fill in more than one at the same time
How should I fill in multiple
thank you
<img width="850" alt="1" src="https://user-images.githubusercontent.com/70124937/165450239-e38c39cb-b322-4321-9844-838e7c031220.png">

**Comment by adizanni** [comment]
Hello @Chen2022, you need to use the Object Groups. 
You can follow this tutorial: https://youtu.be/eAbaDfNw93M
Basically you create an Object Group (with a name: ex. "chair") and you list the member objects one by one. Then you can reference the object group in the entity Object field using the angle bracket (ex: <chair>). Of course if the object is composed by too many object this is not practical, but there is a workaround using the plugin ExportToHASS (putting an # at the end of the name of the object); please check the documentation.

**Comment by Chen2022** [comment]
ok thank you
