### ISSUE TITLE
can I customize and fix the sun position

### ISSUE THREAD

**Issue by Chen2022** [adizanni/floor3d-card#104]
Hello, can I customize and fix the sun position

**Comment by adizanni** [comment]
Yes you can change the "north" parameter to give the position of your home. Based on the latitude and longitude you have put as Home Assistant parameter, the sun elevation and postion will be calculated automatically.

Example of north parameter:

```yaml
north:
  x: -1
  z: 0
```
And the reference axis are like this:

![image](https://user-images.githubusercontent.com/35622920/165900408-cec3dfcf-bb51-4709-8c68-62fa3592e339.png)

**Comment by Chen2022** [comment]
OK, thank you

**Comment by FragMenthor** [comment]
> Yes you can change the "north" parameter to give the position of your home. Based on the latitude and longitude you have put as Home Assistant parameter, the sun elevation and postion will be calculated automatically.
> 
> Example of north parameter:
> 
> ```yaml
> north:
>   x: -1
>   z: 0
> ```
> 
> And the reference axis are like this:
> 
> ![image](https://user-images.githubusercontent.com/35622920/165900408-cec3dfcf-bb51-4709-8c68-62fa3592e339.png)

Hello!
Can you please elaborate on the settings of this parameter?
What's the range? For each axis?

For instance, this is my house:
![image](https://github.com/adizanni/floor3d-card/assets/74264069/40af55fc-a0ec-4020-83c3-8da31f4ad010)

The way I have drawn it, it is rotated 42º to the left, so the north is 42º to the right

![image](https://github.com/adizanni/floor3d-card/assets/74264069/3ba8518c-82c6-4537-960b-d3e42fe4bc51)

What values should I use?
Thanks in advance!
