### ISSUE TITLE
Some object IDS cannot be obtained

### ISSUE THREAD

**Issue by Chen2022** [adizanni/floor3d-card#106]
I can't get the hair object of this mannequin anyway. I tried to combine the objects into one object according to the tutorial, but I didn't succeed. I must be stupid and didn't understand the tutorial. It's convenient for me to guide or help me combine the objects. Thank you very much! I put the mannequin below.
<img width="861" alt="01" src="https://user-images.githubusercontent.com/70124937/166099692-be799fb9-f165-4813-a078-4f261acccdb3.png">
<img width="850" alt="02" src="https://user-images.githubusercontent.com/70124937/166099694-80007da2-f23f-4582-a357-4de6fc2ed2fd.png">
<img width="929" alt="03" src="https://user-images.githubusercontent.com/70124937/166099697-a4247747-aae6-47e6-a443-63d65b273760.png">
[female02.zip](https://github.com/adizanni/floor3d-card/files/8596531/female02.zip)

**Comment by adizanni** [comment]
Hello @Chen2022 , I do not think you are stupid, you went already very far. The mannequin is not easy to group (my procedure works but it is cumbersome and need to be repeated every time you change the model). When you have to do that I really suggest you to move to [my plugin](https://github.com/adizanni/ExportToHASS) that support the possibility to export an object as a whole by appending a # to the object name. After that you will be able to hide the mannequin in the card based on presence (for instance). Of course if you do that you will not be able to work on single elements (like the hair).

**Comment by Chen2022** [comment]
You're great. You made it
