### ISSUE TITLE
transparent

### ISSUE THREAD

**Issue by xfyisheng** [adizanni/floor3d-card#107]
Background Color:transparent

**Comment by adizanni** [comment]
I have to change the code for that: what do you want to achieve ?

**Comment by xfyisheng** [comment]
Transparent theme, so beautiful and beautiful

**Comment by adizanni** [comment]
@xfyisheng ,please check  the new release (v1.4.2) there is a transparent background.......

**Comment by diamant-x** [comment]
It works fine from my side.
Maybe is worth to update the docs to mention that just writing "transparent" and not a hex code would make it work? I first tried using a ARGB hex code like this one https://gist.github.com/lopspower/03fb1cc0ac9f32ef38f4 but it failed. 

<html>
<body>


backgroundColor | string | '#aaaaaa' | canvas background color
-- | -- | -- | --



</body>
</html>

**Comment by adizanni** [comment]
I close as I assume that the new release is managing the transparent background, beware of the custom themes, I'm not sure if this works well with them. I've tested succesfully in the default and dark standard themes.
