### ISSUE TITLE
Feature Request: Multiple objects inside "object_id" field

### ISSUE THREAD

**Issue by marrobHD** [adizanni/floor3d-card#11]
**Is your feature request related to a problem? Please describe.**
This feature request is realted to my comment on issue: https://github.com/adizanni/floor3d-card/issues/1#issuecomment-862889818

I wrote about that some some furniture inside Sweet Home 3D are constructed with multiple objects with having a group objects feature inside SH3D in mind.

Until the Sweethome3D plugin comes, I would suggest/request a "multiple objects in the object_id field feature".

**Describe the solution you'd like**
Multiple objects inside "object_id" field separed by spaces/commas.

**Describe alternatives you've considered**
Waiting for the Sweethome3D plugin @adizanni mentioned

**Comment by marrobHD** [comment]
Thanks for your fast implemention!

I forgot to mention, that I also need working and type3d: show/type3d: hide.
That's why I asked for multiple object id's inside the object_id field.

It's cool that we can now toggle lights which are only on the floorplan and dont have an id in HA...

That's how I would like to use the group configuration.
![grafik](https://user-images.githubusercontent.com/29308361/122774839-d92f6500-d2a9-11eb-9226-9ffda06cdd6d.png)

My suggestion now would be to add a new configuration option called "object_group" to all type3d properties like lights, show, hide, etc.

**Comment by adizanni** [comment]
This is exactly how it works; you just need to change your entity this way:

```
entities:
  - entity: sensor....
    type3d: show
    show:
      state: ....
    object_id: <briefkasten>

instead of using an object_id in the entity config, you need to reference your object_group enclosed in <>

**Comment by marrobHD** [comment]
Yap, sorry. I missed it somehow. Thanks!
