### ISSUE TITLE
New Action: Toggle

### ISSUE THREAD

**Issue by Newlance** [adizanni/floor3d-card#112]
**Is your feature request related to a problem? Please describe.**
I would like the ability to toggle a light on/off by tapping on it, rather than opening up the more info 

**Describe the solution you'd like**
Similar to other floor-plan solutions, it would be great if I could tap/click to toggle and/or long press to get more-info for devices such as switches, covers, and lights.

**Describe alternatives you've considered**

**Additional context**
The more-info is nice, but takes you away from the blueprint, especially if you are working on a mobile device or touch screen device

**Comment by Newlance** [comment]
Just figured out the gesture bit which mostly solves this issue; however, it only seems to work on mobile device. 
When I try to use it on my computer, clicking the device brings up the popup with the object name (ie: living_room_lamp_5)
Is it possible for 1 click / 1 tap toggle to work on mobile and PC? 
Thank you,

**Comment by adizanni** [comment]
Hello @Newlance, yes I see that some of the requests you did are already implemented.  The default behaviour is that the action is triggered by "double click" and "double tap" but you can put the click: 'yes' parameter at the card level to set the "click" and "tap" as default behaviour and you can change the default action at the entity level with the Action parameter.

**Comment by Newlance** [comment]
Ah, thank you! Great work again! :)

**Comment by ndbroadbent** [comment]
Argh I finally figured it out! I cloned the repo and started looking at the code and I figured out that click actions don't work when Lovelace is in edit mode. That's where the `Object:` alerts are coming from:

```
  private _defaultaction(intersects: THREE.Intersection[]): void {
    if (intersects.length > 0 && intersects[0].object.name != '') {
      if (getLovelace().editMode) {
        window.prompt('Object:', intersects[0].object.name);
      } else {
        ...
```

That was a bit annoying! I'm going to change this in my fork so that it shows the object ID in the console logs but still performs the default action. Like this:

```
if (getLovelace().editMode) {
        console.log('Object:', intersects[0].object.name);
      }
    
      this._config.entities.forEach((entity, i) => {
        if (entity.type3d == 'light' || entity.type3d == 'gesture' || entity.type3d == 'camera') {
          for (let j = 0; j < this._object_ids[i].objects.length; j++) {
            if (this._object_ids[i].objects[j].object_id == intersects[0].object.name) {
              if (entity.type3d == 'light') {
                this._hass.callService(entity.entity.split('.')[0], 'toggle', {
                  entity_id: entity.entity,
                });
              } else if (entity.type3d == 'gesture') {
                this._hass.callService(entity.gesture.domain, entity.gesture.service, {
                  entity_id: entity.entity,
                });
              } else if (entity.type3d == 'camera') {
                fireEvent(this, 'hass-more-info', { entityId: entity.entity });
                //this._hass.states[entity.entity].attributes["entity_picture"]
              }
              break;
            }
          }
        }
      });
```

**Comment by adizanni** [comment]
It seems a fair change you can do a pull
