### ISSUE TITLE
Text is mirrored after converting OBJ to GLB

### ISSUE THREAD

**Issue by Newlance** [adizanni/floor3d-card#119]
**Checklist:**

- [ ] I updated to the latest version available
- [ ] I cleared the cache of my browser

**Release with the issue:**

**Last working release (if known):**

**Browser and Operating System:**

**Description of problem:**
I wanted to see what performance enhancements occur from converting from obj to glb.
Having one file is preferable, I also noticed transparency on images seems to be working which is a big plus!
however all the text appears to now be upside-down and backwards which is unfortunately a deal breaker.
This wouldn't be a problem with frames, but I'm not sure what can be done about text on 3D objects.
Is there a workaround that you're aware of?

Alternatively, is there a way to get transparency in images working in the obj format?
If you see the third screenshot attached, that's what I'm looking for; however, in obj format the transparent background seems to convert to a dark grey.

Also, I'm using your SweetHome3D HA Plugin to get the OBJ file in the first place, if that matters.

Thank you!

**Additional information:**
![image](https://user-images.githubusercontent.com/25864289/182659895-a507f891-908c-4445-af87-d8076c080937.png)
![image](https://user-images.githubusercontent.com/25864289/182660339-fad2c2dc-3ca0-4189-b7f3-4f661b65b6ad.png)
![image](https://user-images.githubusercontent.com/25864289/182660500-f7a9f51f-1f6b-41da-9d68-5f756f4970bf.png)

**Comment by adizanni** [comment]
Hello @Newlance, this is a known problem that I have not yet had the time to fix. GLB has never left its experimental support due to lack of time; I'm not yet ready to spend more time on the card for the coming days (leaving to holidays). I've seen that in your repository you have some skills in 3d, are you, by any chance available to become a contributor to this card project ?

**Comment by Newlance** [comment]
@adizanni  I've certainly been thinking about it. As you may have noticed I have a lot of ideas Lol
Not a lot of experience with the library you're using, but given some time I'm sure I could learn.

**Comment by Newlance** [comment]
Created PR https://github.com/adizanni/floor3d-card/pull/122 to resolve this issue!

**Comment by Newlance** [comment]
Closing with merge. hurrah!

**Comment by adizanni** [comment]
Hello @Newlance thanks a lot for the work, you dared to put your hands in my crappy code, you would deserve a price.........
