### ISSUE TITLE
Hide the floors button?

### ISSUE THREAD

**Issue by Newlance** [adizanni/floor3d-card#120]
I would like to create a "fake" room underneath each floor so that I can have stairs leading to the floor below.
Is there a way to hide the "change floors" buttons?

I decided to break each floor up into its own OBJ file to boost performance; however I'm encountering issues because SweetHome3D doesn't allow downward leading stairs without a lower floor beneath it.

![image](https://user-images.githubusercontent.com/25864289/182979712-f2657607-2fee-4976-b92a-151f88ea7dc4.png)
![image](https://user-images.githubusercontent.com/25864289/182979744-93c5075c-f473-4c5a-808d-7c76baf25928.png)

**Comment by adizanni** [comment]
It is not yet possible, but I may think about hiding the controls or hiding one specific floor

**Comment by Newlance** [comment]
Created PR for this item https://github.com/adizanni/floor3d-card/pull/121

**Comment by Newlance** [comment]
Closing with merge!

**Comment by adizanni** [comment]
Thanks for this too....
