### ISSUE TITLE
Losing Floor after adding certain entities

### ISSUE THREAD

**Issue by Polcdev** [adizanni/floor3d-card#124]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:**

**Last working release (if known):**

**Browser and Operating System:**
Windows 11, Chrome Version 104.0.5112.81 (Official Build) (64-bit)

**Description of problem:**
All working fine, but I have added this specific Entity and map to a light fixture the floor disappears. Light works but lose floor in all floorplan. 

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by adizanni** [comment]
Hello @Polcdev how many lights you defined in your model ? 

bear in mind that when you activate the shadows, this is consuming a lot of PC resources and you can only have in your scene a number of lights than is less than the number of "Max Texture Image Units" you will find in this report https://webglreport.com/?v=2,
