### ISSUE TITLE
BUTTON LEVELS DO NOT APPEAR

### ISSUE THREAD

**Issue by VITCHEPF** [adizanni/floor3d-card#127]
**Checklist:**

- [x ] I updated to the latest version available
- [ ] I cleared the cache of my browser

**Release with the issue:**
V 1.4.4
**Last working release (if known):**

**Browser and Operating System:**
CHROME - WINDOWS 10

**Description of problem:**
I'am working with .GLB file. After update Home Assistant the buttons levels are not appearing at the top left of the 3d canvas.
I cleared the cache and nothing changed.

HA Actual Version
Home Assistant 2022.8.7
Supervisor 2022.08.5
Operating System 8.5
Frontend: 20220802.0 - latest

![IMG](https://user-images.githubusercontent.com/73760504/187058824-753a350f-6193-47af-b19c-9727ca45198a.jpg)

**Comment by ndbroadbent** [comment]
This is happening for me with `.glb` files as well. When I use `.obj` and `.mtl` files the level buttons appear correctly (but the model takes much longer to load)

**Comment by ndbroadbent** [comment]
@VITCHEPF It just started working for me. I switched to using the `.obj` and `.mtl` files, and then switched back to `.glb` and the level buttons were still present. I also closed the Sweet Home 3D app and reopened it, and the exported again. I'm not sure what exactly fixed it, but it's now working for me.

<img width="976" alt="Screen Shot 2022-09-08 at 11 58 06 PM" src="https://user-images.githubusercontent.com/139536/189116249-d70b35d9-0590-45d2-9e58-b9ddb08f4230.png">

<img width="1020" alt="Screen Shot 2022-09-08 at 11 58 36 PM" src="https://user-images.githubusercontent.com/139536/189116320-17b424d0-ed2a-49f6-a940-0099b9f919b0.png">

**Comment by ndbroadbent** [comment]
Ah this was the commit that broke it: https://github.com/adizanni/floor3d-card/commit/c000babf23210508eb4045caa92e02c358e4889d

You need to have `hideLevelsMenu: 'no'` in your config otherwise they are hidden by default. The condition should be updated to be`!= 'yes'` instead of `== 'no'`.

**Comment by VITCHEPF** [comment]
Hi @ndbroadbent, thanks for your support.

My Floor-3D plugin was working perfectly, until I did the HA update indicated in the bug report.
After this update the level menu disappeared.

I prove to check many things:  hideLevelsMenu: 'no' is correct in my config, I've already tried to use the obj + mtl version, I've uninstalled and reinstalled the plugin, I've cleared the cache several times, but the levels menu still hidden.
I've tried everything you can imagine, but the problem persists.

In this moment, I changed hideLevelsMenu: to 'yes', Closed the browser, Clearead the cache, Reopen the HA, Changed hideLevelsMenu: to 'no' and suddenly "Voila", the levels menu reappeared....

Unbelievable !

![Sem título](https://user-images.githubusercontent.com/73760504/189195908-36fd0333-cba0-414f-90d0-8d3cb96935a3.png)
