### ISSUE TITLE
Is it possible to have "hidden" light sources for down lights?

### ISSUE THREAD

**Issue by ndbroadbent** [adizanni/floor3d-card#129]
This is related to #84. I'm working on the first level of my floorplan, and I'm not sure how to set up downlights in the ceiling:

<img width="395" alt="Screen Shot 2022-09-04 at 12 00 19 AM" src="https://user-images.githubusercontent.com/139536/188269506-cfe3b61e-de90-4002-a0aa-9d4497ef8a6f.png">

I found these ceiling light models, but I don't like how they are floating there. Is there a way to create an invisible downlight to light up the rooms, and click on the floor to control the lights? Thanks!

**Comment by ndbroadbent** [comment]
I created a transparent disc in Blender and exported a `.dae` file:

<img width="509" alt="Screen Shot 2022-09-09 at 12 08 55 AM" src="https://user-images.githubusercontent.com/139536/189118149-73678099-8eac-4131-8a7e-7150cf751ae8.png">

I can also stretch it to make fluorescent tubes:

<img width="365" alt="Screen Shot 2022-09-09 at 12 09 22 AM" src="https://user-images.githubusercontent.com/139536/189118264-7c535558-95d2-4465-95da-65528da817b7.png">

I like how it's almost invisible but you can still see it. I think it should be possible to make it completely transparent as well, and then click on the floor or walls to toggle the lights.

<img width="782" alt="Screen Shot 2022-09-09 at 12 09 45 AM" src="https://user-images.githubusercontent.com/139536/189118338-0bbbd7ed-737f-4b53-a5e1-663f24ccfcc8.png">

**Comment by hitnrun30** [comment]
@ndbroadbent would you mind sharing your disc file.  I dont have blender, just fusion 360 and they are not friendly with exporting obj files with content and texture.

**Comment by ndbroadbent** [comment]
@hitnrun30 Sure!

* Here's a ZIP of the `.obj` and `.mtl` files: [ceiling-light-invisible.obj.mtl.zip](https://github.com/adizanni/floor3d-card/files/9691441/ceiling-light-invisible.obj.mtl.zip)
* Here's a zip with a Collada (DAE) file you can import into Sweet Home 3d: [ceiling_light_invisible.dae.zip](https://github.com/adizanni/floor3d-card/files/9691438/ceiling_light_invisible.dae.zip)\
* And here's the Blender file in case anyone needs it: [ceiling-light-invisible.blend.zip](https://github.com/adizanni/floor3d-card/files/9691444/ceiling-light-invisible.blend.zip)

**Comment by adizanni** [comment]
@hitnrun30 @ndbroadbent should we close this one ?

**Comment by hitnrun30** [comment]
Yes, I was able to make it work.
