### ISSUE TITLE
Double click doesn't work

### ISSUE THREAD

**Issue by HFsi** [adizanni/floor3d-card#134]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
1.5.0
**Last working release (if known):**
1.4.2
**Browser and Operating System:**
Windows 10 with Chrome and Firefox

**Description of problem:**
After upgrading to the latest release, the double click action doesn´t work anymore, so I can´t get the objects name

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by mese16** [comment]
Same Problem.

Checklist:

  I loaded to the latest version available
  I cleared the cache of my browser

Release with the issue:
1.5.0
Last working release (if known):
none 
Browser and Operating System:
MacOS Monterey Safari, Chrome, Firefox

**Comment by adizanni** [comment]
Hello guys, this works by design since version 1.5.0; look at this pull description https://github.com/adizanni/floor3d-card/pull/130.
