### ISSUE TITLE
Robot vacuum cleaner mapping in real time

### ISSUE THREAD

**Issue by ovidiu4** [adizanni/floor3d-card#137]
Hi guys!

I have recently discovered this plugin and i must say that it is amazing. I have a lot of electronics in my house that i would like to see and interact with from within the floor3d card.

The most interesting idea i had was to add a Xiaomi Roborock to the plan and have it move in real time as it is cleaning the house.
There are already a lot of plugins that can get exact coordinates from vacuum cleaners like the "xiaomi-vacuum-map-card" and "xiaomi cloud map extractor"

So we can get the exact position of the vacuum cleaner at any time. 
All that is needed is to somehow add a 3d model to the plan and have it move

What do you think?
I can help test and maybe some (light) coding

**Comment by Christianb233** [comment]
Hi ovidiu4, it was a good idea; did you have the chance to acheive this project ?

**Comment by ovidiu4** [comment]
> Hi ovidiu4, it was a good idea; did you have the chance to acheive this project ?

I think that they were working to implement this feature but i kind of gave up on this project... It might be already done by the dev team

**Comment by adizanni** [comment]
Hello guys, it is a good idea but not an easy one to implement. Is there already an entity type that provides coordinates in the attributes ?

**Comment by ovidiu4** [comment]
Hello, i am using the Xiaomi Cloud Map Extractor and as far as i can see there are no easily accessible entities with the coordinates... I am sure you can get these somehow from the cloud

I would be willing to help test and debug, but coding is not my biggest strength :)
