### ISSUE TITLE
Light problem

### ISSUE THREAD

**Issue by ozzy071988** [adizanni/floor3d-card#143]
Hi!

I have a problem with light.

The lighting penetrates the walls and illuminates the room next door.

I remember in previous versions I didn't have this problem, the light stayed in the room

![light issue](https://user-images.githubusercontent.com/35668350/201542959-3f26cb53-e93f-465b-82bd-d1278d08106d.png)

**Comment by adizanni** [comment]
Hello @ozzy071988, in order for lights to stop at walls you need to put shadow: 'yes' in the parameter of the  card and /or in the parameter of the light.

**Comment by ozzy071988** [comment]
Shadows for card solves the problem, 

thank you
