### ISSUE TITLE
Current position and rotation of the camera

### ISSUE THREAD

**Issue by zzaal** [adizanni/floor3d-card#146]
> "When in edit mode you can double click in an empty model space to retrieve the current position and rotation of the camera." 

The double click option does not work

The popup window with coordinates does not appear.
After the successful setup, I didn't edit the plan for a while.
When the breakdown happened, after updating your version or after updating HA, I do not know
Previously, everything worked and the window appeared, now it doesn't.
How do I get the camera coordinates now?

**Comment by adizanni** [comment]
Hello @zzaal , please look at this issue https://github.com/adizanni/floor3d-card/issues/142. There was a change in v1.5 that was not done by me, I have accepted it and I should have looked at more options, many people have complained and found issues. Unfortunately these days I have no time to fix or even to change the documentation. I'm scared that this change is limiting the adoption of the card.

**Comment by zzaal** [comment]
Ou! Its fine!
editModeNotifications: 'yes'
its work again
THX
