### ISSUE TITLE
Walls gets black when I turn on a light

### ISSUE THREAD

**Issue by lexcao1729** [adizanni/floor3d-card#149]
Everything gets black when turn on a light.
Is this because there are too much entities of light? 
There are 25 entities.
Most of them is like this:
`  - entity: light.tz3210_s1x7gcq0_ts0502b_light_4
    type3d: light
    object_id: Ceiling_lampcorridor2_2
    light:
      lumens: ‘300'
      shadow: 'no'
      distance: ‘300'
      decay: '2'`
<img width="928" alt="截屏2023-02-19 20 29 26" src="https://user-images.githubusercontent.com/89396980/219948077-7513607a-6ad8-4568-b0ad-7591c811ca59.png">
Light on.
<img width="958" alt="截屏2023-02-19 20 29 46" src="https://user-images.githubusercontent.com/89396980/219948092-6c90b870-d020-4502-b20a-8df762b5c530.png">
Light off.

**Comment by adizanni** [comment]
Black walls are a sign of the WebGL lacking memory resource to complete the rendering.
There is a limitation of the number of lights only if you are using the shadow :"yes" globally and for each of the lights. It does not seem to be the case for you (shadow: "no" at least for the light in the example). Try to remove some of the light entities and check at which point it starts popping black walls. Also please open the web developer console on the browser and tell me if you see any error message.

**Comment by lexcao1729** [comment]
Remove light entities doesn't help.
But I change the lumens and distance of lights to same value, and the problem is solved.
It seem there shouldn't be too much different values in lumens and distance.
