### ISSUE TITLE
TypeError: Attempting to define property on object that is not extensible.

### ISSUE THREAD

**Issue by bsp9493** [adizanni/floor3d-card#150]
Current Version of HASS
Home Assistant 2023.2.5
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230202.0 - latest

Sweethome3d version 7.02

Fresh install of floor3d from HACS

followed your online tutorial Episode 3 https://www.youtube.com/watch?v=4qrDpDnPK6I

Unfortunately I get the following 2 errors when I try to save my initial card.

  TypeError: Attempting to define property on object that is not extensible.
  TypeError: Attempted to assign to readonly property.

I'm guessing I missed a step or did not install some dependancy.  Unfortunately I was not able to find reference to these two issue with floor3d.

What did I do wrong?  Your help is appreciated!

dave

**Comment by adizanni** [comment]
Hello @bsp9493, one problem that is happening frequently is that, starting from the sample people forgets to remove the objects and object groups of the sample model.

**Comment by bsp9493** [comment]
There we go!!!

Problem solved!

Thank you:)

d
