### ISSUE TITLE
HA_2023.4.0 not displayed FloorPlan

### ISSUE THREAD

**Issue by zzaal** [adizanni/floor3d-card#153]
Hello!
After updating HomeAssistant to version 2023.4.0. Floorplan is not displayed in Lovelace, I see an empty space.
When rolling back to 2023.3.6. or earlier, everything is displayed normally.
The developers have changed something in Lovelace.
I ask you to adapt your excellent integration for the new version 2023.4.0.
Thank you in advance!

**Comment by FragMenthor** [comment]
Same here! Help?

**Comment by peteh** [comment]
Same in my instance after updating

**Comment by adizanni** [comment]
I will look into it during the week end.

**Comment by tidalf** [comment]
Thanks (I love your card). it fails here for me : 
"return 0 != t.getElementsByTagName("HUI-PANEL-VIEW").length"

**Comment by adizanni** [comment]
Loaded a fix in release 1.5.2, please do some test, I had no time to do extensive tests. Test in all card condition (sidebar, panel, masonry, etc). Thanks all

**Comment by FragMenthor** [comment]
> Loaded a fix in release 1.5.2, please do some test, I had no time to do extensive tests. Test in all card condition (sidebar, panel, masonry, etc). Thanks all

Thanks!!!! All working on my side! You are THE BEST!
🙏🙏🙏

**Comment by zzaal** [comment]
Version 1.5.2 everything works!
Thank you very much!!!
