### ISSUE TITLE
Version 1.5.2 there is no management of the devices

### ISSUE THREAD

**Issue by zzaal** [adizanni/floor3d-card#154]
It is not possible to control devices on the plan.
the statuses are displayed correctly, but it is impossible to turn on/off on the plan with the mouse.
Now only display and no control.

------------------------------------------------------------------------------------------------------------

Logger: frontend.js.latest.202304061
Source: components/system_log/__init__.py:257
First occurred: 05:10:21 (1 occurrences)
Last logged: 05:10:21

http://192.168.0.52:8123/hacsfiles/floor3d-card/floor3d-card.js?hacstag=361776538152:2288:20659 Uncaught TypeError: Cannot read properties of null (reading 'editMode')

**Comment by adizanni** [comment]
It seems that you jumped directly from 1.5.0 to 1.5.2. Enter once in the editor and save your config. It should work better

**Comment by zzaal** [comment]
> It seems that you jumped directly from 1.5.0 to 1.5.2. Enter once in the editor and save your config. It should work better

No, I used version 1.5.1 and updated it yesterday to 1.5.2.
I am creating a new card with a plan, but it is also impossible to manage devices on it.

**Comment by adizanni** [comment]
Ok, and box the uncaught error is ?

**Comment by zzaal** [comment]
I dont understand you, sorry...

**Comment by adizanni** [comment]
I was asking you what was the error in the console, but you already wrote it in the comment, you have still the editMode error

**Comment by hashmaker1982** [comment]
here same error , i try come back older version of both ha and floor3dcard , but no image loaded

**Comment by zzaal** [comment]
on version HA_2023.3.6 and 1.5.1 all worked.
Then I upgraded to HA_2023.4.1 and 1.5.2 and now the plan is displayed in Loelace, the devices change their status on the plan only if they are turned on from native cards.
On the plan itself, you can't control the devices, only mono to see them.
The cash tap on the plan gives an error in the HA logs.

**Comment by adizanni** [comment]
I think I know the root cause, but I cannot fix it before tomorrow, please be patient, ha changed ui objects in 2023.4 and unfortunately they do not have stable API for all needed functions and they make the life of the custom card developers harder and harder

**Comment by hashmaker1982** [comment]
here np. i just revert oldest version cause im in setting up the card right now , so i can have the time to do my card perfect. Ty for the awesome work

**Comment by zzaal** [comment]
Thank you very much!
Of course, as soon as you have time, we will wait.
Your card is the best, there are no analogues!

**Comment by hashmaker1982** [comment]
today i  enjoy with vr-glasses and my home project ... awesome walking in my real home but in vr

**Comment by hashmaker1982** [comment]
i was thinking : theres a way to pair a lovelace in a 3d object ? example . i want open both cctv cams when i click on a monitor in the 3d model , i already have a button in main view that do it and i think if is possible and how

**Comment by zzaal** [comment]
THX!
1.5.3. works!!!

**Comment by adizanni** [comment]
@zzaal, you are fast, my HACS is not yet showing the new release

**Comment by hashmaker1982** [comment]
here too confirm that work well ty
