### ISSUE TITLE
no light at all in iphone 

### ISSUE THREAD

**Issue by hashmaker1982** [adizanni/floor3d-card#155]
hi , i noticed that the model that i upload in the local folder of my hass istance , work so well if i run from a imac 2015 , but , idk why  , when i try to open in my iphone12 i noticed that can control all the smart paired devices , but on light , no lights effect at all , no shadows , nothing , i've try to : 
- put extralightmode on 
- set the max lumens for each light spot
- set diffent kinds of colors ( warm white , yellow )
- try change a lots of lamps in sh3d 
any suggest ?? im the only one that have this problem?

**Comment by adizanni** [comment]
Hello @hashmaker1982 , I cannot reproduce it on my iPhone SE, I try to do some research. Are you using an iPhone browser or Home Assistant companion app ?

**Comment by hashmaker1982** [comment]
both , in iphone 12 but i found out my error right now , was the decay parameter that I had overlooked
btw ty
