### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Grosscoder** [adizanni/floor3d-card#157]
Logger: frontend.js.latest.202306080
Source: components/system_log/__init__.py:257
First occurred: 8:30:59 AM (1 occurrences)
Last logged: 8:30:59 AM

http://homeassistant.local:8123/hacsfiles/floor3d-card/floor3d-card.js?hacstag=361776538153:2356:4517 Uncaught Error

**Comment by adizanni** [comment]
I would need more info, if you started from the sample model and you have tried to load your model, please do not forget to remove all references to the sample model (all entities and object groups)

**Comment by adizanni** [comment]
Please @Grosscoder without a comment before the week-end I will close the issue

**Comment by Grosscoder** [comment]
its still not working

**Comment by adizanni** [comment]
Hello @Grosscoder , I need more info, have you tried to do what I asked in previous comments ?

**Comment by Grosscoder** [comment]
Yes I removed everything but it's still not working

**Comment by adizanni** [comment]
Can you please add the YAML of the card ?

**Comment by Grosscoder** [comment]
I will do it tomorrow in office.

**Comment by Grosscoder** [comment]
this is my yaml
type: custom:floor3d-card
path: /local/www/3d/
name: Home
objfile: plain home.obj
lock_camera: 'no'
header: 'yes'
click: 'no'
overlay: 'no'
backgroundColor: '#aaaaaa'
hideLevelsMenu: 'no'
globalLightPower: '0.8'
shadow: 'no'
extralightmode: 'no'
show_axes: 'no'
sky: 'no'
overlay_bgcolor: transparent
overlay_fgcolor: black
overlay_alignment: top-left
overlay_width: '33'
overlay_height: '20'
north:
  x: 0
  z: -1
camera_position:
  x: 609.3072605703628
  'y': 905.5330092468828
  z: 376.66437610591277
camera_rotate:
  x: -1.0930244719682243
  'y': 0.5200808414019678
  z: 0.7648717152512469
camera_target:
  x: 37.36890424945437
  'y': 18.64464320782064
  z: -82.55051697031719
object_groups: []
entities: []
zoom_areas:
  - zoom: ''

**Comment by Grosscoder** [comment]
and this is what i am getting.
[image: Screenshot 2023-11-26 202051.png]

**Comment by adizanni** [comment]
Try to put your object file name within simple quotes ''.

If you have used the export to obj function, you should also have an mtl file in your folder, put the name of it in the mtlfile field.

I do not see other issues.

Andy

**Comment by Grosscoder** [comment]
Thanks, I'll do that.

**Comment by Grosscoder** [comment]
It's still not working

**Comment by adizanni** [comment]
Sorfry I noticed only now the URL /local is pointing to /config/www folder in home assistant, so you need to put /local/3d in the path

**Comment by Grosscoder** [comment]
Ok, I'll check it out.

**Comment by Grosscoder** [comment]
Thanks  🙏 it's working.
You're the best.
