### ISSUE TITLE
card doesn't show level selector for multi-level model, and i "can't" separate levels because of stairs between levels

### ISSUE THREAD

**Issue by mcmikemn** [adizanni/floor3d-card#159]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
HA: 2023.7.2
HACS: 1.32.1
floor3d-card: 1.5.3

**Last working release (if known):**

**Browser and Operating System:**
Firefox/Lnux

**Description of problem:**
When I export a multi-level model, floor3d-card imports and displays all 3 levels - the level-selector UI doesn't appear. 

In one of your videos (maybe https://www.youtube.com/watch?v=4qrDpDnPK6I or https://www.youtube.com/watch?v=qumPsCVpyUU), you say not to export a model with levels because floor3d-card might not handle them correctly. So I copied my .sh3d file into 3 files, and in each one I deleted the extra 2 levels so that each file had only 1 level.

The problem is that I have stairways between levels, and when I delete a level to which the stairway belongs, the adjacent level no longer displays the stairway, or even a "hole" in the floor where the stairway should be.

The same thing happens if I mark a level as un-viewable in SH3D instead of deleting it. I'm concerned that even if I can get floor3d-card to display the level-selector UI, it's going to hide a level the same way SH3D does: by also hiding the stairway from the adjacent level.

I realize this may not be an issue, and may instead be a request for support - if so, is there a forum or a way to communicate regarding support issues and questions?

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by adizanni** [comment]
Hello @mcmikemn, when you export with the export to ha plugin and you include the home.json file, the levels should work. The level is a property of the object, so, yes, the behavior is the same as in sweet home. If the stairway belong to level 1, it will appear when level 1 is selected. I do not see how I can change this behavior.
Or maybe I did not get the issue.

**Comment by mcmikemn** [comment]
Oh! I was exporting straight from SweetHome3D - I wasn't aware of your export plugin. I installed it and exported with it, and the level selector UI shows up in floor3d-card. Yay! (floor3d-card thinks one of my objects, a window on the 2nd floor, belongs to the basement level, but I bet that has something to do with naming - I'll look into that separately).

FYI, floor3d-card hides levels better than SweetHome3D does: in SweetHome3D, if I hide my Basement level and show my First Floor level, then the stairs that belong to the Basement are hidden and the hole in the floor where the stairs were on the First Floor disappears as well, so my First Floor looks like there never were stairs and there is no level below it. But when floor3d-card hides the Basement level, the floor of the First Floor has a hole in it where the stairs were. That's fine!

Thanks for the help, again, @adizanni!

**Comment by adizanni** [comment]
Happy it is working this way. Think you can close the issue?
