### ISSUE TITLE
Failure to Load obj File

### ISSUE THREAD

**Issue by stephengolub** [adizanni/floor3d-card#16]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:** 0.9.10

**Last working release (if known):** 0.9.10

**Browser and Operating System:**
Chrome Windows
Home Assistant iPadOS App

**Description of problem:** I added more to my model in SweetHome3D and exported it. The card loads, shows "2/2 100%" then sits. Looking in the console, looks like there's an error.

**Javascript errors shown in the web inspector (if applicable):**

```Start Build Renderer
floor3d-card.js:976 End Build Renderer
floor3d-card.js:976 Material loaded start
floor3d-card.js:976 Material loaded end
floor3d-card.js:976 Object loaded start
floor3d-card.js:976 Add Objects
floor3d-card.js:976 element: {"object_id":"Door_499"}
floor3d-card.js:976 element: {"object_id":"sweethome3d_opening_on_hinge_1_doorOutside_528"}
floor3d-card.js:976 element: {"object_id":"sweethome3d_opening_on_hinge_1_doorOutside_516"}
floor3d-card.js:976 Uncaught Error
    at floor3d-card.js:976
    at Object.onLoad (floor3d-card.js:976)
    at XMLHttpRequest.<anonymous> (floor3d-card.js:976)```

```

**Additional information:** Seems like some try..catch or something could help. But a better indicator in the UI would be good, too...

Obviously it's something in my model, I'm slowly removing items and re-exporting to see which part is breaking it.

**Comment by adizanni** [comment]
I agree that the code lack the basics (try catch), instead of debugging by yourself do not hesitate to share your obj and config. This will allow me to have more test cases and it is easier for me to debug. If you trust me with your model I will use it only for test and debug purposes

**Comment by stephengolub** [comment]
Sure, I don't mind sharing the model and config with you, lemme get something set up.

**Comment by stephengolub** [comment]
I just had an "a ha" moment and tried something and it worked.

Basically the root cause was having invalid object ids in the entity config. So I imagine the card is looking up the object without actually checking to see if it exists.

**Comment by adizanni** [comment]
I close this issue. For release 1.0 i'm tiding up the code and put some control in the card editor and card loader.
