### ISSUE TITLE
Excellent work!

### ISSUE THREAD

**Issue by pittbull** [adizanni/floor3d-card#160]
This is really good work and I am trying to wrap my head around all the functionality :)

As much in my house is related to presence of people I am trying to experiment with show/hide based on this, but it seems they are limited to binary_sensor and I am using device_tracker to handle presence.

Is there anyway to make use of other classes than binary_sensor?

**Comment by adizanni** [comment]
@pittbull you can always transform trackers into binary sensor vis templated sensor. You have also the possibility to use template calculations via Javascript code (check the guide) but I'm not recommending it because it is experimental and may lead to security breaches

**Comment by adizanni** [comment]
Without comment from the user in more than one month, I close the ticket
