### ISSUE TITLE
How to rotate a ceiling fan?

### ISSUE THREAD

**Issue by avishayil** [adizanni/floor3d-card#163]
**Is your feature request related to a problem? Please describe.**

Currently, there doesn't seem to be a straightforward way to rotate wings of a ceiling fan using the Floor3D card in Home Assistant.

**Describe the solution you'd like**

I would like to see a feature added to the Floor3D card that allows users to easily rotate the wings of the ceiling fan. This could be achieved by integrating a 'fan' entity or use the existing 'rotate' entity.

**Describe alternatives you've considered**

I haven't tried any alternatives

**Comment by adizanni** [comment]
Hello @avishayil , the rotate feature is quite flexible, have you tried it, is there something that is unclear about its usage ?

**Comment by adizanni** [comment]
Hello @avishayil , without any comment from the user in more than one month, I close the ticket
