### ISSUE TITLE
Can't Add more one light entity in the same plants

### ISSUE THREAD

**Issue by Drwood73** [adizanni/floor3d-card#165]
**Checklist:**

- [Home Assistant 2023.8.4
Supervisor 2023.08.1
Frontend 20230802.1 - latest ] I updated to the latest version available
- [ already try] I cleared the cache of my browser

**Release with the issue:**
Relase Home Assistant: Home Assistant 2023.8.4
Supervisor 2023.08.1
Frontend 20230802.1 - latest

Relase floor3d-card (aka Your Home Digital Twin) v. 1.5.3

**Last working release (if known):**

**Browser and Operating System:**
Windows 11 Google Chrome 

**Description of problem:**
I obtain the error down when i try to add more than 2 entities light (all work correctly if i add only one light)
Logger: frontend.js.latest.202308021
Source: components/system_log/__init__.py:270
First occurred: 4 settembre 2023 alle ore 01:00:14 (55 occurrences)
Last logged: 17:37:17
https://10.9.1.4:8123/local/community/floor3d-card/floor3d-card.js:2356:4517 Uncaught Error
https://10.9.1.4:8123/local/community/floor3d-card/floor3d-card.js:2356:4523 Uncaught Error

**Javascript errors shown in the web inspector (if applicable):**
Finished with errors: check the console log
in the console log under system/registry i find this error: 
https://10.9.1.4:8123/local/community/floor3d-card/floor3d-card.js:2356:4523 Uncaught Error

```

```

**Additional information:**

**Comment by adizanni** [comment]
Hello try to provide the Yaml card configuration code.

**Comment by Drwood73** [comment]
type: custom:floor3d-card
path: /local/CasaWood/
name: P1
objfile: P1.obj
lock_camera: 'no'
header: 'yes'
click: 'no'
overlay: 'no'
backgroundColor: '#aaaaaa'
hideLevelsMenu: 'no'
globalLightPower: '0.8'
shadow: 'no'
extralightmode: 'no'
show_axes: 'no'
sky: 'no'
overlay_bgcolor: transparent
overlay_fgcolor: black
overlay_alignment: top-left
overlay_width: '33'
overlay_height: '20'
north:
  x: 0
  z: -1
camera_position:
  x: 609.3072605703628
  'y': 905.5330092468828
  z: 376.66437610591277
camera_rotate:
  x: -1.0930244719682243
  'y': 0.5200808414019678
  z: 0.7648717152512469
camera_target:
  x: 37.36890424945437
  'y': 18.64464320782064
  z: -82.55051697031719
object_groups:
  - object_group: RoundTable
    objects:
      - object_id: Round_table_1
      - object_id: Round_table_2
      - object_id: Round_table_3
  - object_group: EntranceDoor
    objects:
      - object_id: Door_9
      - object_id: Door_7
      - object_id: Door_5
entities:
  - entity: switch.lsalotto
    type3d: light
    object_id: sweethome3d_opening_on_hinge_1_Light_wall_art_head_Black_paint_96_556
  - entity: switch.lcucina
    type3d: light
    light: {}
    object_id: border_695
zoom_areas:
  - zoom: ''
mtlfile: P1.mtl

**Comment by adizanni** [comment]
Hello, first of all, If you havé loaded your own model you should remove the object groups, because they are referring to the sample model. Second, your second light has {} after the light attribute, this is not correct.
Let me know if it helps.

**Comment by adizanni** [comment]
Without a feedback from the user in more than one month, I close the ticket.
