### ISSUE TITLE
Can not get it to load obj or glb file

### ISSUE THREAD

**Issue by Bidarin412** [adizanni/floor3d-card#166]
![error](https://github.com/adizanni/floor3d-card/assets/99785413/24336f3c-eaa1-41e9-a455-f566c5897962)

Hello, I can't get it to load up in dashboard card. So this is what I did, I used **ExportToHASS** plugin, unzip it, uploaded 2 files .obj and .mtl to www folder in hass, type in path and file name, but it just doesn't load. Please guide me if I do anything wrong here.

**Comment by adizanni** [comment]
When you load the model created via the example, you have to remove all the objects from the sample (ex Object groups and entities referring to the sample model)

**Comment by adizanni** [comment]
Without a comment from the user in more than 1 month, I close the ticket
