### ISSUE TITLE
The model is trying to load images that the export does not export oO

### ISSUE THREAD

**Issue by alexandrechoske** [adizanni/floor3d-card#167]
![image](https://github.com/adizanni/floor3d-card/assets/47279355/4ca4be0c-7fca-4724-9451-5d189d0f28dd)

![image](https://github.com/adizanni/floor3d-card/assets/47279355/8d2e699f-ba93-40ec-8b25-8507fc3bb10b)

Hi guys, my model is trying to load some images that the export tool is not exporting at all...

There are about 5 images that I dont have, but the model is trying to read, so this ends up in a gray image without the home.

Note these "home_pics", I dont have it, but the model is trying to render...
Is there another way to export it to generate those images?

**Comment by adizanni** [comment]
First time I see this.  Try to see the result with the sh3d export to obj function and compare the exported files. Other option is to send me the sh3d file.

**Comment by alexandrechoske** [comment]
Hi Adizanni, I just compared both and is basically the same result.

31 x 30 ( HA x SH )

And also I dont have the "home_pics" on SH export as well.

Im sendin you the file so you can test it on your enviromnent..


https://drive.google.com/file/d/10DARYDrjd7641zA83C_S3bMNan_x4IkZ/view?usp=sharing

**Comment by adizanni** [comment]
Your first test exclude a problem coming from the  custom plugin ExportToHASS.
There is probably something in your model that is not correctly exported, either some names with special characters or some corrupted texture. I will try to check your model over the weekend, in the meantime try to do some tests by removing the texture of some room floors.
Andrea

**Comment by alexandrechoske** [comment]
@adizanni I figured it out, my SH was outdated.
But now I have the background gray everytime...
I will try to search to see someone had it also..

![image](https://github.com/adizanni/floor3d-card/assets/47279355/a96e1e1f-bc90-4f1a-98e9-1c68f74b3e92)

**Comment by adizanni** [comment]
You sitll need the material file (it is mandatory)
