### ISSUE TITLE
Curtains: Movement

### ISSUE THREAD

**Issue by FragMenthor** [adizanni/floor3d-card#168]
**Is your feature request related to a problem? Please describe.**
This integration/card is one of my favorites, and I already use almost every feature that is available (color, doors, windows, lights switches, text, ...). But there is one feature I would like to see and I think it's missing: the ability to reflect the state of curtains.

**Describe the solution you'd like**
A way to have curtains reflect their state on the model.

**Describe alternatives you've considered**
I know there is a "cover" entity to play with, but it only seems to apply to "up" ou "down" movement. Is there any way to use this type of object interaction?

**Additional context**
I don't know if it's possible to "stretch" part of an object:
![image](https://github.com/adizanni/floor3d-card/assets/74264069/435d97e3-186e-4887-beb7-159143c9828d). That would be a solution if possible.

THANK YOU for your card :) !

**Comment by adizanni** [comment]
hello @FragMenthor , it is already an enhancement request (https://github.com/adizanni/floor3d-card/issues/164)
