### ISSUE TITLE
Failed to execute 'define' on 'CustomElementRegistry': the name "mwc-notched-outline" has already been used with this registry

### ISSUE THREAD

**Issue by justinhunt1223** [adizanni/floor3d-card#169]
**Checklist:**

- [x] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:**

Current
[floor3d-card-modified.txt](https://github.com/adizanni/floor3d-card/files/13367629/floor3d-card-modified.txt)

**Last working release (if known):**

**Browser and Operating System:**

**Description of problem:**

Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "mwc-notched-outline" has already been used with this registry

**Javascript errors shown in the web inspector (if applicable):**

```
Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "mwc-notched-outline" has already been used with this registry
    define scoped-custom-element-registry.js:44
    Ct floor3d-card.js:40
    Ct floor3d-card.js:40
    r floor3d-card.js:1
    <anonymous> floor3d-card.js:222
```

**Additional information:**
I'm trying to work on some changes and have the development environment setup with vscode. I updated home assistant to pull floor3d-card.js from http://localhost:5000/floor3d-card.js. The untouched file from the repo works this way. Once a change is made and floor3d-card.js is rebuilt, the error above appears and home assistant throws an error about the floor3d-card custom element does not exist.

To build the new js file, I ran npm start in the vscode terminal, is this the correct command? I attached the new compiled file for reference.

**Comment by adizanni** [comment]
Hello @justinhunt1223 , in my project this is the command I use in terminal to compile the Typescript: 

```
npm run lint && npm run rollup
```

**Comment by adizanni** [comment]
I cannot reproduce the issue so I close the ticket, if you have more info, reopen and I will do the investigations

**Comment by adizanni** [comment]
Closain
