### ISSUE TITLE
Camera setting will not work fine if the Sweethome3D model upper left corner is not at 0,0 coordinates

### ISSUE THREAD

**Issue by sheminasalam** [adizanni/floor3d-card#17]
Hi, I need some help with the camera settings. It seems that even when I copy paste a particular camera position into the code, the default position is not the same. Please check the gif and do advice.
![ezgif-3-a40a16d78934](https://user-images.githubusercontent.com/45196177/123532251-45d2b580-d729-11eb-9dab-42d2ab3addf1.gif)

**Comment by adizanni** [comment]
Hello, I'm having some trouble to reproduce your issue. Maybe there  is something about your model that is by default appearing very small. Do you  mind share it ?

**Comment by sheminasalam** [comment]
no issues...I have attached the files.
[3d.zip](https://github.com/adizanni/floor3d-card/files/6721115/3d.zip)

**Comment by adizanni** [comment]
There is something weird with your model that is offsetting all camera positions. You have probably some objects in the model that are in the space, maybe not visible, Try to recreate a new model with copy paste by selecting only the objects that are actually in the floor plan. I will dig further, I'm not able to reproduce in my  models.

**Comment by sheminasalam** [comment]
I have tried copy pasting the model but it still has the same issue. I am sharing the model file so that you can go through.
[2nd floor.zip](https://github.com/adizanni/floor3d-card/files/6721159/2nd.floor.zip)

**Comment by adizanni** [comment]
Found an explanation even though I think it is a bug that I need to fix. Please move your 2D floor model in a way to have the upper left corner at 0,0. Your current model has something like -4,-3. Do not forget to clear your cache or add a version on obj and mtl file (ex. objfile: 23k8.obj?ver=1) when you change your model

**Comment by sheminasalam** [comment]
This worked for me. Thanks for the quick response.

**Comment by adizanni** [comment]
Even if it does not seem this issue is not an easy one and because there is a workaround I will set it as a feature to work on later
