### ISSUE TITLE
I do not see the menu of the floor levels

### ISSUE THREAD

**Issue by Sived80** [adizanni/floor3d-card#175]
Congratulations for the excellent integration!!!
I don't see the levels menu.
I created a basic model in SH3D:
Floor 0: walls, and an object
Floor 1: walls, and an object.
The only objects are called t0 and t1 and are correctly associated with the level.

![SH3D](https://github.com/adizanni/floor3d-card/assets/81388068/a5ae6682-0bbf-465b-9b8f-4859d575765a)
[test.zip](https://github.com/adizanni/floor3d-card/files/14525197/test.zip)
[Floor 3D card settings.txt](https://github.com/adizanni/floor3d-card/files/14525195/Floor.3D.card.settings.txt)

I'm using SH3D v6.6, your exposure plugin.
I have carried out multiple tests with various models and different browsers always with negative results.
Thank you

**Comment by adizanni** [comment]
Hello @Sived80, sorry my previous comment (that I edited) was wrong. If you have all files copied correctly to the target www folder, it should work. I will do some tests

**Comment by Sived80** [comment]
Hello. I tried to implement the 3D model kindly provided by an online user. In their Home Assistant, it displays the floor plan menu. In mine, it does not. Thank you again for the time you are giving me.

**Comment by Sived80** [comment]
Hello. I tried to implement the 3D model kindly provided by an online user. In their Home Assistant, it displays the floor plan menu. In mine, it does not. Thank you again for the time you are giving me.

**Comment by adizanni** [comment]
Hello @Sived80 , I've also tested with a sample model and it is working. 

![image](https://github.com/adizanni/floor3d-card/assets/35622920/5405be20-9b07-4e91-90ed-8d5e970dabc6)

I've checked your export and in the obj file the name of the objects are not tagged with the level, so this means that the exportToHASS plugin is not doing his job properly. In order to test that I need your sh3d file too

**Comment by adizanni** [comment]
I've also created a very simple model and levels are appearing:

![image](https://github.com/adizanni/floor3d-card/assets/35622920/7f950f38-58c3-461c-9f32-e6be412ad9ef)

**Comment by adizanni** [comment]
I'm not sure if this is a problem I would need to re-debug the plugin, but have you tried to rename the objects 10 and 11 to names with alphanumeric numbers ? For instance "o10" and "o11"

**Comment by Sived80** [comment]
Hi, I installed a parallel instance of Home Assistant alongside the existing one, with only your plugin inside, but there's no news. What I find strange is that even the model downloaded from the internet (working for the user) doesn't show the floor menu in my Home Assistant. The model was already exported with your tool for SH3D.

Could you kindly share the model (already exported from SH3D) with 4 floors that you used to perform the tests? I would like to exclude a problem on the HA side.

From what I can understand, does the exportToHASS plugin add an attribute to the name of the objects? Could you provide me with such an explanation? I could create a small model to test the correct functionality in HA.

[pippov6.6.zip](https://github.com/adizanni/floor3d-card/files/14623005/pippov6.6.zip)

**Comment by adizanni** [comment]
Can you tell me the version of the plugin you are using ? You can find it in SweetHome3D, menu Help -> About -> Libraries. It should be like this:

![image](https://github.com/adizanni/floor3d-card/assets/35622920/e8acb0a8-8e5e-4a99-a794-278fb7326e42)

v0.1.0.

My export produces the exptected behaviour:

![image](https://github.com/adizanni/floor3d-card/assets/35622920/d072d471-225b-430d-8d26-de1cbdd3b629)

**Comment by Sived80** [comment]
Hello, you're absolutely right!!! I don't know why the add-on is at version 0.0.3. I've fixed the issue, and now everything works. Thank you again for the time you've dedicated. 🙌🏼🙂 Diesci!!!
