### ISSUE TITLE
Q: How to bind door or cover to specific state?

### ISSUE THREAD

**Issue by keeema** [adizanni/floor3d-card#178]
Hi,

I am configuring garage door and gate and I would like to use cover functionality but I don't see any way how to control when it is open and when close.

Type hidden has hide.state for this purpose, e.g.
 - entity: binary_sensor.garazova_vrata_kontakt
    type3d: hide
    object_id: <GarazovaVrata>
    hide:
      state: 'on'

But how to provide the state to cover?

- entity: binary_sensor.garazova_vrata_kontakt
    type3d: cover
    object_id: <GarazovaVrata>
    cover:
      pane: <GarazovaVrataTop>
      side: up

**Comment by adizanni** [comment]
Hello @keeema, when you define a cover you need to put an entity of the cover domain (not binary_sensor). If you use the cover domain, the card will automatically retrieve the state from the cover object open/close/percentage open, etc.

**Comment by keeema** [comment]
Thank you for explanation. 
And what are all the acceptable values for door and what for cover?

**Comment by adizanni** [comment]
Door is always associated to a binary sensor so, values are on and off. Cover is always associated to a cover entity and it uses the percentage open attribute to position the cover object at the right place
