### ISSUE TITLE
Cannot import SweetHome3D project

### ISSUE THREAD

**Issue by krzpl** [adizanni/floor3d-card#179]
Cannot import even simple project with one object
Info from HA card: "Finished with errors: check the console log"

Log:
Uncaught error from Chrome 124.0.0.0 on Windows 10 Error Object.onError (/hacsfiles/floor3d-card/floor3d-card.js:2288:34179) XMLHttpRequest.<anonymous> (/hacsfiles/floor3d-card/floor3d-card.js:2231:436056)
Uncaught error from Chrome 124.0.0.0 on Windows 10 Error /hacsfiles/floor3d-card/floor3d-card.js:2356:4523 Object.onLoad (/hacsfiles/floor3d-card/floor3d-card.js:2231:531795) XMLHttpRequest.<anonymous> (/hacsfiles/floor3d-card/floor3d-card.js:2231:435962)
Uncaught error from Chrome 124.0.0.0 on Windows 10 Error /hacsfiles/floor3d-card/floor3d-card.js:2288:34333 Object.onLoad (/hacsfiles/floor3d-card/floor3d-card.js:2231:531795) XMLHttpRequest.<anonymous> (/hacsfiles/floor3d-card/floor3d-card.js:2231:435962)

Newest version of HA: 2024.4.3
Newest version of floor3d-card 1.5.3
Newest version of SweetHome3D: 7.3
Checked with native export to OBJ format and with newest ExportToHASSPlugin.sh3p plugin (this same error)

**Comment by CmdFelipeLira** [comment]
Hi @krzpl !

I had the same problem and I fix it just removing all the objects and group objects automatically created after the import process. Check it and I hope this solve this problem.

**Comment by krzpl** [comment]
Unfortunately without result. Some other bug should exist

**Comment by CmdFelipeLira** [comment]
Please share the card settings screens, if possible. I think that could be something about the directory (folder with .obj .mtl and other files) and object references.

**Comment by krzpl** [comment]
![2024-04-18_16h10_50](https://github.com/adizanni/floor3d-card/assets/93813702/208cbb2b-d8f3-4d6e-a415-7dd52d806d12)

![2024-04-18_16h09_49](https://github.com/adizanni/floor3d-card/assets/93813702/ac3b4665-223d-44f8-b80c-21fb39aae58a)

**Comment by adizanni** [comment]
Please share the entire yaml code of your card by clicking on the code editor

**Comment by krzpl** [comment]
type: custom:floor3d-card
path: /local/floorplan/
name: Home
objfile: home.obj
lock_camera: 'no'
header: 'yes'
click: 'no'
overlay: 'no'
backgroundColor: '#aaaaaa'
hideLevelsMenu: 'no'
globalLightPower: '0.8'
shadow: 'no'
extralightmode: 'no'
show_axes: 'no'
sky: 'no'
overlay_bgcolor: transparent
overlay_fgcolor: black
overlay_alignment: top-left
overlay_width: '33'
overlay_height: '20'
north:
  x: 0
  z: -1
camera_position:
  x: 609.3072605703628
  'y': 905.5330092468828
  z: 376.66437610591277
camera_rotate:
  x: -1.0930244719682243
  'y': 0.5200808414019678
  z: 0.7648717152512469
camera_target:
  x: 37.36890424945437
  'y': 18.64464320782064
  z: -82.55051697031719
object_groups:
  - object_group: RoundTable
    objects:
      - object_id: Round_table_1
      - object_id: Round_table_2
      - object_id: Round_table_3
  - object_group: EntranceDoor
    objects:
      - object_id: Door_9
      - object_id: Door_7
      - object_id: Door_5
entities:
  - entity: binary_sensor.iphone_krzysiek_focus
    type3d: door
    object_id: <EntranceDoor>
    door:
      doortype: swing
      direction: inner
      hinge: Door_3
      percentage: '90'
  - entity: binary_sensor.iphone_ela_focus
    type3d: hide
    object_id: <RoundTable>
    hide:
      state: 'off'
  - entity: light.taras_kule
    type3d: light
    object_id: Bowl_2
    light:
      lumens: '800'
zoom_areas:
  - zoom: ''
mtlfile: home.mtl
objectlist: home.json

**Comment by krzpl** [comment]
type: custom:floor3d-card
path: /local/floorplan/
name: Home
objfile: home.obj
lock_camera: 'no'
header: 'yes'
click: 'no'
overlay: 'no'
backgroundColor: '#aaaaaa'
hideLevelsMenu: 'no'
globalLightPower: '0.8'
shadow: 'no'
extralightmode: 'no'
show_axes: 'no'
sky: 'no'
overlay_bgcolor: transparent
overlay_fgcolor: black
overlay_alignment: top-left
overlay_width: '33'
overlay_height: '20'
north:
  x: 0
  z: -1
camera_position:
  x: 609.3072605703628
  'y': 905.5330092468828
  z: 376.66437610591277
camera_rotate:
  x: -1.0930244719682243
  'y': 0.5200808414019678
  z: 0.7648717152512469
camera_target:
  x: 37.36890424945437
  'y': 18.64464320782064
  z: -82.55051697031719
object_groups:
  - object_group: RoundTable
    objects:
      - object_id: Round_table_1
      - object_id: Round_table_2
      - object_id: Round_table_3
  - object_group: EntranceDoor
    objects:
      - object_id: Door_9
      - object_id: Door_7
      - object_id: Door_5
entities:
  - entity: binary_sensor.iphone_krzysiek_focus
    type3d: door
    object_id: <EntranceDoor>
    door:
      doortype: swing
      direction: inner
      hinge: Door_3
      percentage: '90'
  - entity: binary_sensor.iphone_ela_focus
    type3d: hide
    object_id: <RoundTable>
    hide:
      state: 'off'
  - entity: light.taras_kule
    type3d: light
    object_id: Bowl_2
    light:
      lumens: '800'
zoom_areas:
  - zoom: ''
mtlfile: home.mtl
objectlist: home.json
``

**Comment by krzpl** [comment]
`type: custom:floor3d-card
path: /local/floorplan/
name: Home
objfile: home.obj
lock_camera: 'no'
header: 'yes'
click: 'no'
overlay: 'no'
backgroundColor: '#aaaaaa'
hideLevelsMenu: 'no'
globalLightPower: '0.8'
shadow: 'no'
extralightmode: 'no'
show_axes: 'no'
sky: 'no'
overlay_bgcolor: transparent
overlay_fgcolor: black
overlay_alignment: top-left
overlay_width: '33'
overlay_height: '20'
north:
  x: 0
  z: -1
camera_position:
  x: 609.3072605703628
  'y': 905.5330092468828
  z: 376.66437610591277
camera_rotate:
  x: -1.0930244719682243
  'y': 0.5200808414019678
  z: 0.7648717152512469
camera_target:
  x: 37.36890424945437
  'y': 18.64464320782064
  z: -82.55051697031719
object_groups:
  - object_group: RoundTable
    objects:
      - object_id: Round_table_1
      - object_id: Round_table_2
      - object_id: Round_table_3
  - object_group: EntranceDoor
    objects:
      - object_id: Door_9
      - object_id: Door_7
      - object_id: Door_5
entities:
  - entity: binary_sensor.iphone_krzysiek_focus
    type3d: door
    object_id: <EntranceDoor>
    door:
      doortype: swing
      direction: inner
      hinge: Door_3
      percentage: '90'
  - entity: binary_sensor.iphone_ela_focus
    type3d: hide
    object_id: <RoundTable>
    hide:
      state: 'off'
  - entity: light.taras_kule
    type3d: light
    object_id: Bowl_2
    light:
      lumens: '800'
zoom_areas:
  - zoom: ''
mtlfile: home.mtl
objectlist: home.json
`

**Comment by adizanni** [comment]
You have to remove the object groups they are referring to the sample model

**Comment by krzpl** [comment]
![2024-04-20_10h03_43](https://github.com/adizanni/floor3d-card/assets/93813702/b8f4c0e4-97f8-49a5-82c2-ab005eea2f7d)

**Comment by adizanni** [comment]
Have you removed the object groups ?

**Comment by krzpl** [comment]
![2024-04-21_20h59_21](https://github.com/adizanni/floor3d-card/assets/93813702/70f098d4-86fa-418f-9540-a38d28ac107e)

object groups cannot be removed, should exist

**Comment by adizanni** [comment]
I mean remove the object groups coming from the sample project of course the object_groups field has to stay....

**Comment by krzpl** [comment]
![2024-04-22_16h18_03](https://github.com/adizanni/floor3d-card/assets/93813702/c7d92ace-bfd4-471b-9c8d-123f2b975c18)
![2024-04-22_16h20_51](https://github.com/adizanni/floor3d-card/assets/93813702/2dcef195-9fff-487f-bb9a-39e2179d3a69)

Sample objects removed but problem still exist

**Comment by adizanni** [comment]
You removed too much. Now you need to redeploy the card with HACS or copy back the files in the floor3d-card folder. What I meant, in your card configuration you need to remove all references to the sample project. This is done by either remove the object groups in the UI editor or remove all object groups in the yaml configuration (you have to keep the object_groups keyword). I suggest you recreate a card from scratch and you use the UI editor to remove the object groups and entities that refer to the sample project

**Comment by adizanni** [comment]
I'm sorry but I have no time to help you with visual aids

**Comment by krzpl** [comment]
OK, now I understand what should be removed. After that my own project was imported correctly :) 
Problem was with some default object imported automatically
Thank you for support, problem solved
