### ISSUE TITLE
Plan doesnt show up

### ISSUE THREAD

**Issue by H4rl3k1n** [adizanni/floor3d-card#18]
Hi,

i use a raspi4 with M2 ssd.
Core and Supervisor 6.6, home assistant os 6.1

Roomplan made with sweet home 3d.

I can see the preview in the card, but the room doesnt show up in lovelace?

Allways the same error:

Logger: frontend.js.latest.202106030
Source: components/system_log/__init__.py:190
First occurred: 14:11:52 (3 occurrences)
Last logged: 14:12:50

http://xxx/hacsfiles/floor3d-card/floor3d-card.js?hacstag=3617765380911:1005:586839 Uncaught Error

SC of preview:

![image](https://user-images.githubusercontent.com/63719436/123635681-3bddaf00-d81c-11eb-96ef-d23f00238dcc.png)

Any suggestions? Thanks in advance!

**Comment by adizanni** [comment]
Hello, please show me the content of the Code Editor, when you create the model without any entity, the Editor adds an empty entity that is not well menaged. I have solved this issue in the  the  current opened branch but I have not release it.
Solution is either to add your first entity or manually remove the entity from the code editor.

**Comment by H4rl3k1n** [comment]
hi, thanks for the quick reply.

i cant show you the content of the code editor, the screenshot above was done before the config. After ive added all and saved it the lovelace was empty, absolute empty. Means: even the EDIT button for the roomplane wasnt there, no chance to search for typos or wrong entities. After a few try´s i reseted HA to a snapshot before, and did all again. Extremly word by word. Now it works. I figured out: 
if an entitiy is offline during the setup (f.e. zigbee device is not online after reboot) the error can be enforced. Also this empty entity causes the problem like you mentioned above. 
Reboot (core or system) doesnt help, also to delete the dashboard was no solution: all new made plans having the same error, for me only fallback to an snapshot was helping. 
Maybe you can have an eye on the offline entities: would be ok if the plan is not showing up, but at least you can edit it to remove broken entity or correct typos etc. 
Cheers m8. 
PS: great work at all, looks great, many thanks for this frontend :)

**Comment by adizanni** [comment]
Hello, I will check how to prevent an offline entity to generate a blocking issue. For future reference, the card is entirely working in the client side and it is rare that reboot or recover from a previous snapshot resolve issues. More often you  need to clear browser cache or check for other issues/bugs (as you did in the end). Also be advised that you have the Raw view editor in the top right view menu that give you access to the config of the full view. Is something is wrong with the card and you cannot edit it anymore, use the raw editor...

**Comment by azmat007** [comment]
hi,
i tried all ways to get the OBj file to load. But it doesnt load, it doesnt show up. Restarted many times too but still it wont show. i used the newer version with json file also
![image](https://user-images.githubusercontent.com/47318310/124570899-56d1a400-de58-11eb-9435-f274705ee17c.png)

Let me know what can be done

**Comment by adizanni** [comment]
Hello I suggest that you proceed step by step. I cannot test it at home as I'm away. To start I would remove the json object file, you have put a link to the JavaScript file instead, keep it blank. Second, in order to avoid bugs related to folder names, I suggest you keep it simple, no spaces and no dashes in the path and file names. Also avoid to use my sh3d plugin if you are not willing to experiment anda debug. Then retry, if the model is still not appearing I suggest you send it to me.

**Comment by adizanni** [comment]
Please let me know if the problem is still there. I have done some correction for the management of the first load of the models and I'm not able to reproduce your issue. If I do not receive an answer by Sunday I consider the bug as closed

**Comment by H4rl3k1n** [comment]
for me this case is closed, with the previous version you solved my problem (empty entity). I cant speak for the other case here, but my issue is solved. Thanks.
