### ISSUE TITLE
Not able to group object with id

### ISSUE THREAD

**Issue by Frazou1** [adizanni/floor3d-card#181]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**

**Last working release (if known):**

**Browser and Operating System:**

**Description of problem:**

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by adizanni** [comment]
Hello @Frazou1, I would need more info here (ex. your card yaml config, a link to the model in obj format, etc).

**Comment by Frazou1** [comment]
object_groups:
          - object_group: Salon_light
            objects:
              - object_id: border_510
              - object_id: border_504
              - object_id: border_507
              - object_id: border_501
        entities:
          - entity: light.lumiere_table
            type3d: light
            object_id: Sphere_104_459
            light:
              shadow: 'yes'
              vertical_alignment: bottom
          - entity: light.lumiere_salon
            type3d: light
            light: {}
            object_id: Salon_light

**Comment by adizanni** [comment]
When you refer an object group you need to put it between bracket:

```yaml
- entity: light.lumiere_salon
        type3d: light
        light: {}
        object_id: <Salon_light>
```

**Comment by Frazou1** [comment]
Thanks you so munch ! Working now !
