### ISSUE TITLE
Click on entity with Cellphone doesnt work

### ISSUE THREAD

**Issue by Frazou1** [adizanni/floor3d-card#182]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**

**Last working release (if known):**

**Browser and Operating System:**

**Description of problem:**

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by adizanni** [comment]
The default gesture for light action is the double click (double tap on touch screen). If you want a single click (tap), you need to activate the click option in the card configuration

**Comment by Frazou1** [comment]
Ok that much better but maybe add a note we need to clear cache on the companion app. Thanks !
