### ISSUE TITLE
Object ID madness? All are the same?

### ISSUE THREAD

**Issue by dreimer1986** [adizanni/floor3d-card#186]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:**
v.1.5.3
**Last working release (if known):**

**Browser and Operating System:**
Chrome 132.0.6793.2 Windows 11 24H2

**Description of problem:**
Well to be honest, I have no clue if it's my fault in SweetHome3D or a problem of your Export Addin or in the Addin itself or whatever else... I successfully imported my model into your very promising addin and it shows my floor now. (p.s. I recommend to add a prominent phrase into the readme telling others that entities and object groups shall be replaced by [] in Code Editor mode. Looks like a few older reports all stumbled over this ^^) I started tinkering with the camera calibration and entity import, but here we have a problem. I wanted to assign lights and on every light I click on it opens a popup with the same name. "2"... Just the number. I have named the lights in SH3D and added a description in a slight last hope to get a more useable object ID, but nope... I provide you my current model and OBJ export. Maybe you have an idea?

https://dreimer.eu/other/home3d.7z

p.s. GREAT work. since I tinkered with SH3D to generate images for a floorplan card I dreamt of something like your addin!
 

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

EDIT: Please wait with your reaction. I might have misunderstood the light object differences. Will check later today

**Comment by dreimer1986** [comment]
OK, I tinkered a bit more and tried OBJ export and the addin. Looks like in your Episode 3 of the video tutorial you selected part of the lampshade and got a nice value. I for my side get a 2 on the lamps like the one in the bathroom. But not a unique 2, but several ones, like the lamp in the hallway has the 2, too. So I don't manage to find a unique value to assign to a entity. Is this my wrongdoing?

EDIT: And yes, the file was created with a 7.x SH3D version, but I converted with 6.6

**Comment by dreimer1986** [comment]
So. Some news here. I found out one more thing in need and now reached a first milestone.

For all the others tinkering around in the future, if you are looking for your Object ID for the lights, there are none by default. In Sweet Home 3D go and rename your lights adding a # at the end of each name. Like this:

![image](https://github.com/user-attachments/assets/407f8f8b-844b-485d-9f31-540780757073)

Even more important... If you replace any files of your model and wanna use the new changes... Push F12 for opening the debug console of the browser, right click on refresh and choose "Clear cache and refresh completely." Otherwise your changes will not show up!

This knowledge will fix the Object ID madness for me on lights matters.

But the report can still stay active, even with the same name... Next I wanted to tinker with Object groups and doors... And we are back at the very same problem... The door  between hallway and living room consists of Object IDs 2 (Hinges), 4 (Wood Corpus), 5 (Glasses) and 6 (Door Handle) and these are not unique once more...

And while we are at it, I have a few (more like three ^^) rendering problems, too.

![image](https://github.com/user-attachments/assets/00d004fa-a7cd-4a75-a347-96f2ab059dc3)
This is the Sweet Home 3D rendering. Look at the entrance to the living room. You see a white stripe on the floor there. Better would be some more tiles, but this is inside the wall in theory, so this seems to be not working for SH3D.

![image](https://github.com/user-attachments/assets/ae63bf94-e2b1-43ca-828e-c11c8bfc0e1d)
But better white than nothingness. This is the render in Floor3D. It lets through the transparent backgroiund as there is nothing rendered at all. And the wall has stripes which are not that noticebale, but they are there.

And the last one the living room door causing problems is rendered nicely, too:

![image](https://github.com/user-attachments/assets/fd14f4d5-2ad1-4d92-8996-acf1686ea506)
This is SH3D again. Nice wood texture and same for the doorframe.

![image](https://github.com/user-attachments/assets/868538db-a9de-4a96-936a-1eb5aec023f3)
Floor 3D seems to suggest to paint the door grey though and the doorframe... It chose the texture of the air conditioner as it seems...

This is it for now. Looks like my report more and more becomes a diary to the final goal. If you have any clue regarding how to fix the current status, please tell me. I for myself will not stop trying, too. Maybe I find a solution I can post here, maybe you have a idea... We will fix this :D

**Comment by adizanni** [comment]
Hello @dreimer1986, I will try to tackle your problems in sequence and you tell me if there are things I forget or I did not get right.

FIrst point: in order for the ExportToHASS plugin to work properly, remove all special characters from the object names in SH3D (umlaut is not accepted, only use a-z, A-Z and 0-9). The Sharp (#) at the end of the object names have special meaning in the Export. Use the # when you want your object to be exported as a group and not as each of the object component.

Second point: you are right if the files .obj, .mtl and all texture files (.jpg, etc.) are cached, they will not consider the new version. You can either remove all cached objects (as you did) or append a version tag to the name of the file in the YAML card configuration (ex: objfile: home.obj?version=7, mtlfile: home.mtl?version=10). You change the version each time the file is re-exported.

Once you fix these two points you will be able to redo a test and post here what are the persisting issues.

**Comment by dreimer1986** [comment]
OK, this was more than a big help :D

I removed all äöü, all spaces and all "-" aka a-z, A-Z and 0-9 only in my names. This alone fixed the door textures.

![image](https://github.com/user-attachments/assets/9f319f83-8242-4730-b475-70aeb3b49a52)

Then I realized that all _2 _3 etc names were gone in the json file and the export addin really chose the names I used in SH3D.
That showed me another flaw i still had though. I had quite some objects with identical names. Most were irrelevant as these never are planned to do anything, but still... I renamed all duplicates including some doors that will do something later on... End result: I can create a Object group with unique IDs now and the door really swings open in my test.

![image](https://github.com/user-attachments/assets/ee1121d7-8db3-4c3b-b256-5c8fe50f7a8a)

So one thing is left. The floor in the door frames is transparent aka nothing is drawn there.

![image](https://github.com/user-attachments/assets/6106ee24-100a-4868-8103-732ec6d304ff)

Likely I can find some fix in my model, but it renders differently here, so I thought I mention it.

P.S. I understand what these # are doing here and that it can cause problems when I try to compress the OBJ file for example. For now it's a nice fix as some of the lamps Im used are not that friendly to just choosing the lamps for light emission. I will have to fix that though as I wanna try the compression sooner or later, too.

Still, a big thanks for helping me. Maybe some of these lil traps should be added to the readme files of the according projects. What do you think?

**Comment by adizanni** [comment]
Happy this helped. Yes I have some recurring issues logged by users and I should report them in the documentation. The allowed character rule is mentioned in the ExportToHASS plugin github readme, but it is probably nor clearly expressed...

The gap in the wall it is simply because your floors in SH3D are not extended to cover the surface under the wall. This is happening when you have big doors or holes in the wall that are making the floor visible. The only solution is to extend the floor at the half of the wall from one side and the other. Not sure if it is clear....

I warn you about compression; it is still very experimental and there are many side effects related to object ids and object rendering

**Comment by dreimer1986** [comment]
I understand what you mean with the floor fixing. Will be done asap, but I think we already can close the is report now. Thanks very much :D
