### ISSUE TITLE
Add Support for strip / LED lights

### ISSUE THREAD

**Issue by jampez77** [adizanni/floor3d-card#19]
Is it possible to add support for strip light sources? Currently the light is 'emitted' from the central point of the 3d model. [See this image for example](https://photos.app.goo.gl/p7zk9Bh1hRKNsBEFA).

I think it would look better if there was an option to repeat the 'light pattern' along the entire object.

**Comment by adizanni** [comment]
Hello Jampez, I do not know how you model the strip in Sweethome3D.  If you are able to identify objects composing your strip with an object_id, you can obtain your effect by just creating several entity referring to the same light each with a different object_id or you can create an object_group with all the mentioned objects and assign the group to the entity representing the light (check the doc). 
IF you cannot identify the objects inside the strip then you have to create some fake objects (say, very small cubes) that you place along the strip and that you reference in the card the way I described above. 
In both these cases the source of lights will not be the full strip but each individual object.......

**Comment by adizanni** [comment]
I think that this is not really a feature but more a way to manage grouped objects. There are now several way to make the strip work I propose to close this. Re-open if you think it is really an issue
