### ISSUE TITLE
Use entity state for `globalLightPower`

### ISSUE THREAD

**Issue by jesserockz** [adizanni/floor3d-card#2]
**Is your feature request related to a problem? Please describe.**
I would like to set the global lighting value based on an entity state so that my floorplan outside lighting matches real life.

**Describe the solution you'd like**
Attach the `globalLightPower` to an entity state

**Describe alternatives you've considered**
So far not something that can be configured dynamically

**Additional context**

**Comment by adizanni** [comment]
Done will appear in next release.
