### ISSUE TITLE
suggestions: Groups, dropdown sort

### ISSUE THREAD

**Issue by H4rl3k1n** [adizanni/floor3d-card#21]
Hi,

thanks for the new release. I noticed you made a dropdownmenu for the entitiys, cool idea. Now the broken entitiys wont show up :)

Maybe better with the possibility to search in the dropdown. At the moment its sorted by the first letter and the first hit.
F.e. i search for "light.wohnzimmer", it stops at the first hit with letter l. If i search for "wohnzimmer" theres no hit.
![image](https://user-images.githubusercontent.com/63719436/124385408-be131b00-dcd5-11eb-9a8a-96553889dcd3.png)
Would be better to be able to search for "light" or "wohnzimmer" and all entitys show up with these words.

And i made a group for my speakers in the livingroom. Ive noticed its important to add the <> at the object id, without it doesnt work. I havent found a hint in the manual related to this, maybe you can have a look at the description. Heres the working example:

  - entity: cover.shellyrogso
    entity_template: cover.shellyrogso
    type3d: hide
    object_id: sweethome3d_opening_on_rail_1_Roller_Shutter_Foot_back_119_6_993
    hide:
      state: open
  - entity: media_player.wohnzimmer
    entity_template: media_player.wohnzimmer
    type3d: color
    object_id: < lautsprecher  >
 ** group only works with <>**
    colorcondition:
      - color: yellow
        state: 'on'
object_groups:
  - object_group: lautsprecher
    objects:
      - object_id: '455'
      - object_id: '469'
      - object_id: '477'
      - object_id: '437'
      - object_id: '407'
      - object_id: '423'
      - object_id: Boolean_6_2_371
      - object_id: Boolean_6_2_492
      - object_id: '719'

Thanks in advance.

**Comment by adizanni** [comment]
Hello, related to the braces <> I've put additional instructions in the README (the Youtube tutorial will need a bit of refresh as many things have changed since the video). For sorting the entity list I agree with you, I did a sort() of the entity list but it did not work....... Need to work a little more on it

**Comment by adizanni** [comment]
I've fixed the sort of the object_id in the entity section. Please verify to set for closure

**Comment by H4rl3k1n** [comment]
Hi, with the new release the sort doesnt show up anymore. Ive tryed with IE, Firefox, Chrome with clear cache and fresh restartet server.
I tryed also a complete new 3d-plan, also no dropdown/and/or posibility to sort something.
(Raspberry 4, Core 7.1, Supervisor 6.8, HA OS 6.1)

**Comment by adizanni** [comment]
Yes, I've removed the dropdown for the entity as it was too slow when the number of entities is big. I have kept the dropdown for objects (if you import the  json file) and I have enabled sort for it.

**Comment by adizanni** [comment]
I have an entity dropdown only when there are less than 100 entities
