### ISSUE TITLE
Clickable Switches and Lights Showing in 3D based on Switch and Bulb State.

### ISSUE THREAD

**Issue by timothylarson** [adizanni/floor3d-card#22]
I love the clickable lights and light groups. It would be great to also be able to click objects (and object groups) to be able to control switches as well as to run scripts/automations/scenes.

To go along with this, I would also love to be able to set a condition as to whether a light appears illuminated in the 3d model based on a switch state and bulb state.

Here's a little more contest to this request: Because I have other people in the house who prefer to use physical switches on the wall to control my lights, I have installed smart switches along with my Zigbee smart bulbs. I have automations set so when a switch is powered on it activates a scene that makes sure the bulbs come on at full brightness and a specific set color temp. I also have an automation so when all the lights have been shut off via Zigbee, the smart switch on the wall turns off as well.

The problem I'm having is when a wall switch gets shut off, Home Assistant and zigbee2mtqq just see the bulb as unreachable but the state is still registering as "ON" since that was its state before the power was cut. Since Home Assistant sees the state of the bulb as "ON" it stays on in the 3D card.

Eventually I'd like to swap out all of my wall switches for a smart switch that keeps the bulbs powered but I am waiting for the 
[Inovelli Zigbee Dimmer Switch (Blue Series)](https://community.inovelli.com/t/zigbee-dimmer-switch-project-new-horizon-blue-series/7674) but that isn't available yet.

**Comment by adizanni** [comment]
Hello Timothy, you can use the gesture to do an action on an object to trigger any type of service. Otherwise I would suggest to put device complexity in the backend, not in the card. Your use case with a phisycal switch and a connected bulb can be better managed by a input boolean https://www.home-assistant.io/integrations/input_boolean/ where you control the combination of phisycal and logical states. Maybe I misunderstood your goal...

**Comment by adizanni** [comment]
Please let me know if my answer gives you a workaround to your problem or try to better put additional clarifications. If no answer before the end of Sunday I will close the bug
