### ISSUE TITLE
Color problem

### ISSUE THREAD

**Issue by vring0** [adizanni/floor3d-card#24]
Below is a video demonstrating the problem. When the kettle is in a heating state, it turns orange. When the kettle is off, it should return to its silvery color. After refreshing the browser page, the color of the model is correct. I think this is a bug.

https://youtu.be/ofSqNL5Z8Jw

**Comment by vring0** [comment]
![image](https://user-images.githubusercontent.com/34909289/125944858-281e7e22-82d8-4364-8d2b-92b3001955a8.png)

I found the reason, it is necessary to register the off state in the configuration. You can add a function to return the object color to its original color if state is not true. I thought that if I add one condition and when it is false, the color is returned, and not saved as in my video.

**Comment by adizanni** [comment]
Well spotted, I'm going to load a release where the color is reset to the initial one when the state is not found (sort of 'else').

**Comment by vring0** [comment]
that's what I meant.  Great, I'm waiting for a new release.  In general, as a new feature, I would like to open the HA entity when I click on the object, now you can only call the service

> Well spotted, I'm going to load a release where the color is reset to the initial one when the state is not found (sort of 'else').

**Comment by adizanni** [comment]
Loaded fix in the release 0.9.17, please test and close if ok with the resolution
