### ISSUE TITLE
Light Power, Browser Display problem

### ISSUE THREAD

**Issue by vinz-uts** [adizanni/floor3d-card#25]
Hi, this is a really nice card! I want to report some small problems to help you improve the final effect. The light is too strong (the lumens used are different from those in the real world), the light is too concentrated in a small area, a more diffused effect would be better. Sometimes, if I set too large a lumen value, the light will pass through the wall and illuminate other rooms.
Another problem is that browsers (both firefox and chrome) often block the page and it is necessary to reload the page (I'm using HA on a raspberry 4 with 4GB of RAM and view the browser on another pc - 32GB RAM, good graphics card, etc - in the same local network).
Another problem is the rendering of some furniture textures in Firefox 90.0 which maybe don't load, because the custom furniture (built from cube, cylinder, etc on SH3D) is white. In Chrome all textures are loaded correctly.
Thanks for your work, I hope you will continue to work on this fantastic project!

**Comment by adizanni** [comment]
hello vinz, thanks for all the feedbacks. It is very important for me, as I cannot test all the platforms and navigators. I'm relying on JS libraries that should be as portable as possible (three.js) but I have already noticed differences between Chrome and Safari and between IOS Android, Windows and Linux.

Please help providing evidences (screenshots and configuration) of your problems and sepcifying what is the last version you are using (if it is from HACS); I've done many changes in the last days so it would help to know if you are running on an updated card version or not.

I try to answer one point at a time:

- for the lights I totally agree and there are functions in Three.js to support what you are asking (fading distance is one of them). I will change the behaviour in future releases, trying to limit the impact on existing user cards.
- Related to lights passing through the wall, please verify the degree of transparency of your walls in SH3D (menu 3D View -> Modify 3D view -> set to Opaque).
-  The problem with the blocking would need some screenshot, I cannot reporoduce it. I have noticed that switching to lit 2.0 (last Sunday) the page gets a need to rerender more frequently and I do not understand why, but the way you describe your problem does not seem to refer to lit 2.0
- I will try to start testing in Firefox to verify the problems

**Comment by adizanni** [comment]
After further research I found that the lights passing through the walls is a trickier problem. I'm studying the right resolution but it is not trivial.

**Comment by adizanni** [comment]
loaded a release with shadow management

**Comment by vinz-uts** [comment]
Hi, sorry for the delay time. I try to answer to all questions:
I've downloaded the github repository and manually put the `floor3D-card.js` in the `local/` folder (follow the tutorial video linked in the `readme.md` file). When I've done this, I've downloaded the last commit pushed (a day before opening the issue). I'm thrilled for the fading feature that you're adding. Related to the transparency degree of the wall in my SH3D project: yes, they are already set to Opaque (but I read that you found other causes of the problem). If I can find a power supply for the raspberry, I'll test the new release (just replace the `floor3D-card.js` file?) and I'll take a screenshot loading page problems: usually Firefox and Chrome tell me that the page is taking too long time to reload and it would be advised to block it. Thanks for your work on this card.

**Comment by adizanni** [comment]
It is better to install from [HACS](https://hacs.xyz/docs/installation/installation/). If you cannot or do not want to I recommend to follow always this link: https://github.com/adizanni/floor3d-card/releases/latest and download the floor3d-card.js from the assets section. This way you are sure you are installing the latest version. After having downloaded and replace the exisiting file, it is a good practice to add a label at the end of the resource URL, this way

```yaml
- url: /local/pathtofile/floor3d-card.js?ver=1 (2,3 a different unique number for each new relase)
  type: module
```

**Comment by adizanni** [comment]
Hello there are too many points you are raising please open one ticket for each of the proble, that are persisting. If you agree I close this issue

**Comment by adizanni** [comment]
In the absence of an answer I close the issue, if you want to reopen please be more specific about the problem or open multiple ones if they are different
