### ISSUE TITLE
 You have 1 Lovelace items not loading properly

### ISSUE THREAD

**Issue by edwardtich1** [adizanni/floor3d-card#28]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**

**Last working release (if known):**

**Browser and Operating System:**

**Description of problem:**

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by adizanni** [comment]
Hello Edward, can you be more specific ? Give some logs, screenshot, etc. I have no idea from where to start with your bug description

**Comment by edwardtich1** [comment]
https://yadi.sk/i/iVzZmrt58D1VfQ

**Comment by edwardtich1** [comment]
https://yadi.sk/i/iVzZmrt58D1VfQ

**Comment by adizanni** [comment]
Ok I see. I still do not get if you have installed the card via HACS or local, or both.

Is it a new issue you have because of a recent upgrade of the card ?

can you activate the Web Inspection in you browser and tell me what you see in the console log when you refresh the page with the card ?

**Comment by edwardtich1** [comment]
Custom element doesn't exist: floor3d-card.

**Comment by adizanni** [comment]
Are you sure that the floor3d-card.js file is in /local/floor3d-card/ folder (which corresponds to your /config/www/ in the home assistant home folder ?

**Comment by adizanni** [comment]
Hello I really do not know what to do, I'm sorry

**Comment by adizanni** [comment]
if there is no interaction before Sundahy Iconsider the problem as fixed
