### ISSUE TITLE
Add show config attribute

### ISSUE THREAD

**Issue by jampez77** [adizanni/floor3d-card#3]
Similar to `hide` could we have a `show` attribute for config so an object can be hidden by default and shown when an entity reaches a particular state?

For example I would like to show my EV charger object only when the state is `Charging` so I imagine the config could look something like this:

```
  - entity: sensor.car_charger
    type3d: show
    object_id: car_charge_obj
    show:
      state: 'Charging'

**Comment by adizanni** [comment]
Yes I'm working to put templates so that you will have maximum flexibility. In the meantime I will think to your proposal or an equivalent simple alternative

**Comment by adizanni** [comment]
Added in the new release. I finally adopted your suggested approach (show entity)
