### ISSUE TITLE
The lamp turns on/off by clicking anywhere on the house.

### ISSUE THREAD

**Issue by mcv93us** [adizanni/floor3d-card#32]
**Checklist:**

- [x ] I updated to the latest version available
- [x ] I cleared the cache of my browser

**Release with the issue:**
Latest release v0.10.1b
**Last working release (if known):**

**Browser and Operating System:**
Google Chrome 92.0.4515.131
Windows 10 OS Version 2009 (Build 19043.1151)

**Description of problem:**
I am trying this fabulous project but I have encountered a problem on the actions (gesture); on the test floorplan I am trying to manage a chandelier with a fan, a table lamp and a door sensor.
I want to light up the room when I turn on the light of the chandelier and this works well, I want to turn on / off the light of the desk lamp and this works for me by clicking anywhere on the house also if I click on the chandelier it turns off the light of the chandelier that I had not set for turn on turn off and turn off the desk too.

**Javascript errors shown in the web inspector (if applicable):**
I have no error in the web console.

I have attached the code of the card I created.

```

```

**Additional information:**
Home Assistant is installed as supervised on docker, the HA version is 2021.8.1, as Hardware I use a Raspberry PI 4 with o.s. Raspbian OS 32-bit version of May 7, 2021.

I hope it is enough to understand where the problem is.
[my_floor3d.txt](https://github.com/adizanni/floor3d-card/files/6941713/my_floor3d.txt)

**Comment by adizanni** [comment]
Hello,

when you create an object group you have to reference it with <>, in your case, this is the right syntax:

```yaml
type: custom:floor3d-card
entities:
  - entity: binary_sensor.sensor_ing
    type3d: color
    object_id: frame_151
    colorcondition:
      - state: 'on'
        color: '#ff0000'
      - state: 'off'
        color: '#00ff00'
  - entity: light.sonoff_1000xxxxxx_1
    type3d: light
    object_id: Sphere_1_695
    light:
      lumens: '1000'
  - entity: fan.sonoff_1000xxxxxx
    type3d: gesture
    object_id: <Fan>     
    gesture:
      domain: homeassistant
      service: toggle
  - entity: switch.sonoff_1000yyyyyy
    type3d: gesture
    object_id: Flexo_Cylinder_605
    gesture:
      domain: homeassistant
      service: toggle
object_groups:
  - object_group: Fan
    objects:
      - object_id: CeilingFan5028_2_2_697
      - object_id: CeilingFan6820_3_3_698
      - object_id: CeilingFan_1_1_696
path: /local/home2/
name: My home 3D
objfile: newhome.obj
mtlfile: newhome.mtl
backgroundColor: '#000001'
globalLightPower: 0.4

**Comment by adizanni** [comment]
Release v0.10.2 is out to fix the issue. Well seen, the bug was really bad

**Comment by mcv93us** [comment]
I just updated and now it works perfectly.
I also fixed that forgetfulness about object groups.
Thanks again for this great job !!!

**Comment by adizanni** [comment]
Please close the issue when you are sure that the issue has been solved
