### ISSUE TITLE
Possible to remove name header when not using panel mode?

### ISSUE THREAD

**Issue by sbur83** [adizanni/floor3d-card#34]
**Is your feature request related to a problem? Please describe.**
I have a mobile dash that I'd prefer not to use panel mode with and the header looks ugly and wastes a lot of space.

**Describe the solution you'd like**
Any ideas how to remove?

**Describe alternatives you've considered**
Tried panel mode and I know it's preferred for this card but custom slider row with custom buttons disappear in panel mode for unknown reason. I've tried removing the name from .yaml and it just replaces with original name header.

**Additional context**
Appreciate your work, this card's amazing. Thankyou :)

**Comment by adizanni** [comment]
Hello thanks, I see what I can do

**Comment by adizanni** [comment]
Try to follow this thread https://community.home-assistant.io/t/solved-remove-hide-lovelace-header-custom-header/216117, I'm afraid there is not much I can do inside the card. I close the issue.

**Comment by sbur83** [comment]
Thanks Andy, not really an issue. Cheers
