### ISSUE TITLE
Shadow feature and MAX TEXTURE IMAGE UNITS limitation

### ISSUE THREAD

**Issue by lesydat** [adizanni/floor3d-card#35]
Can you fix light through walls when turn on light?

**Comment by adizanni** [comment]
Hello, starting from recent release, the problem has been fixed by setting the shadow parameter to 'yes'.
Note that the shadow feature is very greedy in PC resources so you may want to see if this is applicable to your model based on the complexity.  Also be aware that, at today, the activation of shadow may have some collateral effect on the lights. To workaround the issue I know give the possibility to set the vertical alignment of the light inside the bound object. This gives the possibility to make a light appear in the case it is shaded by the light object itself.
Please try it and let me know if it works for you.

**Comment by lesydat** [comment]
Turn on shadow make my home model can't load. I use Firefox and my laptop only has Intel graphic

**Comment by adizanni** [comment]
I suspect your problem is similar to the following https://github.com/adizanni/floor3d-card/issues/36.
Can you  please activate the logs and paste here the console content here ? This can be achieved by opening the Web Developer Tools in the Firefox menu

**Comment by adizanni** [comment]
Hello lesydat, please post here the snapshot of the screen you will find here https://browserleaks.com/webgl
This shows the limits you have on your browser related to the number of supported THREE.js (WebGL) objects.

**Comment by lesydat** [comment]
@adizanni 
This is screenshot when turn on shadow
![Floor_plan_-_Home_Assistant](https://user-images.githubusercontent.com/1523631/129604150-e3e53a97-e51b-4482-9d40-2396dfc8d35a.png)

Turn off shadow
![Floor_plan_-_Home_Assistant](https://user-images.githubusercontent.com/1523631/129604251-9648db06-7e97-43ec-bc57-86f9a77eb252.png)

Console log when turn on shadow
<img width="1384" alt="Screen Shot 2021-08-17 at 00 02 11" src="https://user-images.githubusercontent.com/1523631/129604323-c1c9b91c-015b-4484-8ae3-7d4b93465e52.png">

WebGL browser check
![browserleaks-webgl-2021_08_16_23_59_52](https://user-images.githubusercontent.com/1523631/129604468-6e02b121-ea12-45da-96a8-ff897f86e1c6.png)

**Comment by adizanni** [comment]
So, before I see how to optimize the usage of lights and shadows, you will not be able to put more than 16 (Max Texture Image Unit in your WebGL report) lights into your model.  I keep it open for further investigations

**Comment by adizanni** [comment]
Added a new task in project 2.0 to see how to handle lights to consume less GPU resources. Closing the issue as the behaviour of the card is according to THREE.js and WebGL limitation

**Comment by geolos** [comment]
Sorry for my late reply (I come from issue #36). I also confirm that with the shadow set to 'no' the 3D model appears normal. I also attach my WebGL browser check just for reference.
[browser_webGL.pdf](https://github.com/adizanni/floor3d-card/files/7048318/browser_webGL.pdf)

**Comment by adizanni** [comment]
Yes geolos, and do you confirm that you had more than 16 lights defined ?
