### ISSUE TITLE
3D Card limitation

### ISSUE THREAD

**Issue by geolos** [adizanni/floor3d-card#36]
Dear Andy,

I think that I found a bug… It took me almost two days to reproduce it but finally I made it at 3.30am :frowning: :-). It seems that the bug is related with the size of the configuration file that the ‘Live 3D Floor’ can have. If this size/limit is exceeded then the 3D models starts to deteriorate and usually many (if not all) objects are represented as black. In order for you to be able to reproduce it I am supplying you with my configuration and my 3D model. File ‘PartAB’ have the complete configuration which causes problems to the 3D objects due to the limitation that I have explained. Though, if I reduce the size of the configuration file then it works fine. For instance PartA and Part B (which are subsets of PartAB) works excellent, though Part AB which is the unions does not. I will maintain the 3D model in Google Drive for a limited time in case you need it; or anyone else to take ideas 
[https://drive.google.com/file/d/1w20TOZnNC4lVxxC2Dl9a-k9XOMnjaElh/view?usp=sharing)](url)

I hope that you can find a resolution for these. Again excellent work.

BR,
Christos

[PartAB.txt](https://github.com/adizanni/floor3d-card/files/6981206/PartAB.txt)
[PartA.txt](https://github.com/adizanni/floor3d-card/files/6981207/PartA.txt)
[PartB.txt](https://github.com/adizanni/floor3d-card/files/6981208/PartB.txt)

**Comment by adizanni** [comment]
Thanks, I'm going to do some analysis  to detect optimization or define limits.

**Comment by adizanni** [comment]
Hello Christos / Uss, please post here the snapshot of the screen you will find here https://browserleaks.com/webgl
This shows the limits you have on your browser related to the number of supported THREE.js (WebGL) objects.

**Comment by adizanni** [comment]
Please refer to issue #35 as it is a duplicate. I close this one and keep following up from there.
