### ISSUE TITLE
Feature request to open a window on a selected object

### ISSUE THREAD

**Issue by mcv93us** [adizanni/floor3d-card#37]
**Is your feature request related to a problem? Please describe.**
Hello,
is there a way to view the status of an entity like a webcam maybe with a separate screen?
I have two webcams to check and it would be interesting to be able to do it with this card.

**Describe the solution you'd like**
Double clicking on an object should open a window and show the status of the object or in my case the stream of a webcam.

**Describe alternatives you've considered**
n/n

**Additional context**
n/n

**Comment by adizanni** [comment]
If you agree I merge your feature request to this other https://github.com/adizanni/floor3d-card/issues/39.
