### ISSUE TITLE
Feature request to animate objects

### ISSUE THREAD

**Issue by mcv93us** [adizanni/floor3d-card#38]
**Is your feature request related to a problem? Please describe.**
Hello,
the possibility of animating objects would be very interesting,
I have a fan chandelier and I would like the fan blades to spin when I turn it on.

**Describe the solution you'd like**
You should have settings regarding the axis of rotation, the direction of rotation and its speed.

**Describe alternatives you've considered**
n/n
**Additional context**
n/n

**Comment by adizanni** [comment]
Please test new release 1.0.1. I've included a light animation to rotate object based on state (on/off)

**Comment by adizanni** [comment]
Test is succesfull for me: I have not done the direction yet....... Please let me know if the feature request can be closed

**Comment by JVital2013** [comment]
I have some WIP code that will handle rotation speed and direction based off the entity speed/direction. Unless you have other plans I’ll open a pull request in the coming days

**Comment by adizanni** [comment]
No problem for me, as far as you can keep modification small so that I can validate easily. Or if you want to be more involved and rewrite/refactor some of the code (it is getting very crappy) we can target a release 2.0 together.....

**Comment by adizanni** [comment]
I keep the ticket open to follow-up on all additional parameters of this potentially big feature

**Comment by adizanni** [comment]
Ok, thanks @JVital2013 we can close the issue or should we still keep it open and clarify additional requirements ?

**Comment by JVital2013** [comment]
I'm OK with closing it. Have we met your needs @mcv93us?

**Comment by JVital2013** [comment]
At this point we should be able to close this issue

**Comment by adizanni** [comment]
Agree
