### ISSUE TITLE
Remember camera state

### ISSUE THREAD

**Issue by bendikrb** [adizanni/floor3d-card#4]
Awesome work! I've longed for something like this for a long time, after modelling my house in sweethome3d :)

My first (of many, I fear) feature request, is to persist the camera state (possibly utilizing localStorage or the likes).
Perhaps also making it possible to set a default camera position in the card config.

**Comment by adizanni** [comment]
Accepted, will work on it.

**Comment by adizanni** [comment]
Added in new release. Still a manual procedure but works

**Comment by GaoMax** [comment]
Hi, great work!
Unfortunately the camera position doesn't work for me: I double click in edit mode and retrieve this: 
camera_position: { x: -65.36282549580928, y: 2765.0883765575823, z: -934.2915084651966 }
camera_rotate: { x: -1.5628839344749774, y: 0.00017519740014949184, z: 0.02213807336676118 }
But after I enter it in the Code Editor it turns adds '' around the y coordinate. But even after removing it the camera position is not correct and it adds the ' ' back around the y.
camera_position:
  x: -65.36282549580928
  'y': 2765.0883765575823
  z: -934.2915084651966
camera_rotate:
  x: -1.5628839344749774
  'y': 0.00017519740014949184
  z: 0.02213807336676118

**Comment by GaoMax** [comment]
Thanks for the clarification.
If I double click and get the coordinates from an angle and enter them in the config and reload, the picture is completely off. But if I retrieve the coordinates from the reloaded page they match with the ones in the config. Same readings, different angles/rotation?

**Comment by adizanni** [comment]
I may have to retest, I had the impression that the position and rotation were good. Let me check

**Comment by GaoMax** [comment]
#17
Is the issue I had! Moving the upper left corner to 0,0 fixed the issue.

**Comment by adizanni** [comment]
Thanks GaoMax
