### ISSUE TITLE
Mouse position when double click is wrong.

### ISSUE THREAD

**Issue by uspass** [adizanni/floor3d-card#49]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
Any
**Last working release (if known):**
None
**Browser and Operating System:**
All, windows 10

**Description of problem:**
Computed mouse position when double click on an object is wrong. To get the action one has to double click on the left of the object (related to the viewport).
The issue gets worse when camera is far.

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by adizanni** [comment]
Hello Uspass, you are right, I have to check @JVital2013, could this be a side effect of the animationn management ?

**Comment by uspass** [comment]
Hi Andy,

I don't think so. I have noticed this issue long time ago, long before animation. 
I remember I have mentioned it to you once.
It might be in _performAction: 
mouse.x = (e.offsetX / this._content.clientWidth) * 2 - 1;

**Comment by adizanni** [comment]
But do you confirm that this is happening only in View edit mode ? I cannot reproduce it in normal mode and card edit mode. 
This is the standard way to obtain the mouse coordinated in the model:
https://stackoverflow.com/questions/30860773/how-to-get-the-mouse-position-using-three-js

**Comment by uspass** [comment]
It happens in both modes View edit and normal. In card mode is OK.
The following pictures are in normal mode:
![20210829_231717](https://user-images.githubusercontent.com/42880649/131264287-6736c005-ec86-4091-a4bd-f659614e1fed.jpg)
![20210829_231737](https://user-images.githubusercontent.com/42880649/131264293-b3cb8460-26a8-4b12-8743-f4f2af7d98e7.jpg)

**Comment by JVital2013** [comment]
I can confirm that this issue precedes the animation feature. It seems worse in Windows than it is on Mac or mobile. Every code sample I find has that +/- 1, but I don't really understand why it's there mathematically. Maybe we should try removing it and see what happens

**Comment by uspass** [comment]
And this is in normal mode:

Before the double click

![20210829_232158](https://user-images.githubusercontent.com/42880649/131264418-1f6bb96b-9b96-4f8c-adda-735f88404dd3.jpg)

and after the double click

![20210829_232542](https://user-images.githubusercontent.com/42880649/131264432-d1502167-82f9-41fc-b8a9-32ee4abc7e96.jpg)


As you may see I'm clicking outside the object to the left

**Comment by uspass** [comment]
Double clicking here (as in next image) does nothing

![20210829_233057](https://user-images.githubusercontent.com/42880649/131264542-3fa6323c-6136-4cbe-aa53-4dd6ab7da4ed.jpg)

**Comment by uspass** [comment]
I've done some experiments.
Cutting +/-1 doesn't show any difference to me.
But.
It looks like the object is shown in one place but from mouse point of view, is shifted to the left like a ghost object. The shift is like in fixed viewport pixels. When camera is getting close to the object, the issue is less obvious. But when camera is far, the shift becomes important.

![20210830_001446x](https://user-images.githubusercontent.com/42880649/131265584-c403de91-8004-4ad3-a45f-1e4c605e5c54.jpg)

**Comment by uspass** [comment]
I reckon I know what is happening.
Hide HA left panel.
The ghost object goes far to the right. It doesn't even overlap withe the displayed object. 
That means you get wrong viewport coordinates on X axis of the screen.

**Comment by uspass** [comment]
Please discard the last comment as I forgot to refresh after hiding the left panel.

**Comment by adizanni** [comment]
@JVital2013, I really need you here: there has been quite a lot of changes for the management of the resize and left panel, I reproduct the problem that appears always upon resize but 'm not really able to fix.

**Comment by JVital2013** [comment]
I’ll see what I can do!

**Comment by adizanni** [comment]
Hello please, verify if the problem is fixed in v1.1.0 (just released). Thanks @JVital2013

**Comment by uspass** [comment]
It does. Great job. 

Thanks.
us
