### ISSUE TITLE
3D floor plan is not showing

### ISSUE THREAD

**Issue by jjmuriel** [adizanni/floor3d-card#5]
Hi,
I followed the YouTube tutorial to install the custom card, but my floor plan is not displayed in the Home Assistant GUI. I got this error:

```Logger: frontend.js.latest.202106030
Source: components/system_log/__init__.py:190 
First occurred: 12:29:30 (17 occurrences) 
Last logged: 12:37:51

https://my_domain.duckdns.org:8123/hacsfiles/floor3d-card/floor3d-card.js:739:547477 Error
https://my_domain.duckdns.org:8123/hacsfiles/floor3d-card/floor3d-card.js:739:546060 TypeError: undefined is not an object (evaluating 't.states[e.entity].state')
https://local_ip:8123/hacsfiles/floor3d-card/floor3d-card.js:739:547365 Uncaught Error
https://local_ip:8123/hacsfiles/floor3d-card/floor3d-card.js:739:545973 Uncaught TypeError: Cannot read property 'state' of undefined
```

And this is displayed when I'm configuring the card via GUI:
<img width="991" alt="Screen Shot 2021-06-16 at 12 50 39" src="https://user-images.githubusercontent.com/17131600/122268284-7ef56500-cea1-11eb-8673-b941821c2a81.png">

I attached a copy of my SweetHome floor plan exported like Obj.

[Plano 3D-apto.zip](https://github.com/adizanni/floor3d-card/files/6664841/Plano.3D-apto.zip)

Thank you for your help to resolve this issue.

**Comment by adizanni** [comment]
Hello jjmuriel, please remove spaces from the file name when exporting to obj. Also define at least one entity or remove the entities section from the visual editor. I have to fix these things but for the moment, please accept the work around

**Comment by jjmuriel** [comment]
Thank you, but is not working. I get this and the same error:

<img width="991" alt="Screen Shot 2021-06-16 at 15 47 44" src="https://user-images.githubusercontent.com/17131600/122291331-5463d600-ceba-11eb-9070-a941de352189.png">

<img width="1439" alt="Screen Shot 2021-06-16 at 15 50 35" src="https://user-images.githubusercontent.com/17131600/122291608-9ee55280-ceba-11eb-9c74-fe21f8236a0e.png">

```
Logger: frontend.js.latest.202106030
Source: components/system_log/__init__.py:190 
First occurred: 12:29:30 (35 occurrences) 
Last logged: 15:49:36

https://parca.duckdns.org:8123/hacsfiles/floor3d-card/floor3d-card.js:739:547477 Error
https://parca.duckdns.org:8123/hacsfiles/floor3d-card/floor3d-card.js:739:546060 TypeError: undefined is not an object (evaluating 't.states[e.entity].state')
https://192.168.111.10:8123/hacsfiles/floor3d-card/floor3d-card.js:739:547365 Uncaught Error
https://192.168.111.10:8123/hacsfiles/floor3d-card/floor3d-card.js:739:545973 Uncaught TypeError: Cannot read property 'state' of undefined```

**Comment by adizanni** [comment]
This time you did not put the trailing slash in the path:
```
type: custom:floor3d-card
name: TestHome
path: /local/home2/
objfile: Plano3D-apto.obj
mtlfile: Plano_3D-apto.mtl
```

I know; there are a lot of things to be improved

**Comment by jjmuriel** [comment]
Sorry, you're wright, now is working. Thank you very much.

**Comment by adizanni** [comment]
Is it working fast for you ? I develop  using an old laptop, your model take 4-5 seconds to load.

**Comment by jjmuriel** [comment]
I have a MacBook Pro (Retina, 15-inch, Mid 2014) with core I7 gen 4, 16 GB RAM an integrated Intel GPU and takes 2 to 4 seconds charging the model. In my phone (Huawei P40 Pro) takes 4-6 seconds (via Home Assistant mobile app). Once the model was charge the floor plan manipulation is fast in both platforms.

**Comment by adizanni** [comment]
Hello jj, I propose to close the issue, even though I have to fix the  fact that the card visual editor is always  leaving an empty entity which does not work and requires a manual update

**Comment by adizanni** [comment]
As discussed

**Comment by jjmuriel** [comment]
No problem. Thank you @adizanni.
