### ISSUE TITLE
Object ID of ceiling lights

### ISSUE THREAD

**Issue by wishie** [adizanni/floor3d-card#58]
I would like to know how I can find the ID of simple ceiling 'down lights' that arent visible on the model.

**Comment by adizanni** [comment]
Hello wishie, there are other obj viewers where you can see the list of objects. Example: https://3dviewer.net/. Or if you  are not afraid to look into big text files, you can open the obj file in an editor (Visual Studio Code has a obj format  plugin).

If the object is hidden behing other objects you will not find it easily but at least you will narrow down the number of objects and try.
