### ISSUE TITLE
Enable source light group (object selection) - Sweet Home 3D

### ISSUE THREAD

**Issue by jjmuriel** [adizanni/floor3d-card#6]
Hi,
Can you enable source light group like an object to turn it on like a strip light  in floor3d custom card?  Inside my Sweet Home 3D model I created a group of lights on a cornice to simulate an indirect light, but there is not  an object to select in the moment to configure the custom card. Or there is a way to get the object name inside the mtl or obj file? Thanks.

<img width="1552" alt="Screen Shot 2021-06-17 at 9 25 35" src="https://user-images.githubusercontent.com/17131600/122416120-1adcaa80-cf4e-11eb-85da-0f18e083d5ae.png">

**Comment by adizanni** [comment]
The  light entity type creates a PointLight at the center of the box containing the object_id in the model.  The only way to "simulate" a strip ligjht is by creating small objects (ex. cubes) along the path of the strip and bind the light to each of the boxes representiing the strip. Hope it is clearr

**Comment by jjmuriel** [comment]
Thank you , it's clear. I can select the cornice that follows the same path.
