### ISSUE TITLE
Freeze View?

### ISSUE THREAD

**Issue by magnetic157** [adizanni/floor3d-card#60]
Is there a way to "Freeze" the model so it's always in a fixed place and it can't pan, zoom or move?  I don't want to make mine over complicated, I really just want to use a rendered image of the floor plan but combined with this plugin's ability to light up rooms and animate items like fans spinning without having to combine multiple rendered images with picture-elements.

**Comment by adizanni** [comment]
Hello Magnetic, the most I can do is to give a way to disable the camera orbit controls of the mouse or tap gesture, but this will not reduce the size and performances of the model. Unfortunately the three.js library is all or nothing from this point of view

**Comment by adizanni** [comment]
In the absence of an answer and further explanation I consider this feature request as not relevant
