### ISSUE TITLE
Beginner support: Camera position

### ISSUE THREAD

**Issue by aaronganek** [adizanni/floor3d-card#62]
First off, thanks for this amazing card!

I have my OBJ loaded and working well. The starting camera view is looking away from my object. Is there documentation for how best to use the camera position and rotation appearance fields - or a recommended way to export an OBJ from SweetHome3D to center the default camera? When I type in {x:0, y:0, z:0} into the appearance fields, I keep getting NnN positions.

I am sure this is user error - my technical background is limited. Home Assistant is a fun project for me to learn.

Again, thanks for your work here! Really excited to take advantage of it!

**Comment by adizanni** [comment]
Hello @aaronganek , thanks.

coordinate are usually messed up by the THREE.js loader. To avoid this: all objects needs to be at bottom right compared to coordinate 0,0 in the Sweethome3d model (based on the 2d perspective). Also avoid to put objects too far from the focus of your house (ex a tree or a mailbox).

If you have followed the previous guideline, the best way to change the default point of view is:

- When you are in view edit mode, set the view according to your preference (position and rotation of your camera)
- Double click in an area where there are no objects.
- A pop-up will appear
- Copy the test inside the pop-up
- Click the card edit button and enter in code editor for the configuration
- Remove any previous paramater related to the position and rotation
- go to the bottom of the config and paste the copied data
- save

If you follow these 2 steps, you should have the right default view when you open the card

**Comment by adizanni** [comment]
Hello aarong, I close the issue you can follow my procedure above to assist you
