### ISSUE TITLE
1/2: 100%

### ISSUE THREAD

**Issue by SentiHassio1979** [adizanni/floor3d-card#65]
Hi,
![image](https://user-images.githubusercontent.com/60929514/143471650-90cad40b-d1af-4578-92a3-a7bcd51a7771.png)
When selecting the files I just have created I get a "1/2: 100%" message.
Am I doing something wrong?
Thanks

**Comment by adizanni** [comment]
Hello @SentiHassio1979, the error you posted can be anything, from the fact that you are note pointing to the right location of the file, to something more complex like a faulty object in the 3d model.

if you want the problem to be fixed you need to post some more info:


1. The log from the console (in Chrome you access that from the menu More Tools -> Developer Tools)
2. The config of the card
3. The model you are loading (.obj, .mtl)

**Comment by SentiHassio1979** [comment]
> Hello @SentiHassio1979, the error you posted can be anything, from the fact that you are note pointing to the right location of the file, to something more complex like a faulty object in the 3d model.
> 
> if you want the problem to be fixed you need to post some more info:
> 
> 1. The log from the console (in Chrome you access that from the menu More Tools -> Developer Tools)
> 2. The config of the card
> 3. The model you are loading (.obj, .mtl)

Thanks for quick reply. I think I solved the part of 1/2: 100: thanks to the console, apparently my local folder has not been mapped correctly in configuration.yaml. However the card is now fully grey and even when I type in a not existing file name.

Config of the card is
`type: custom:floor3d-card
entities:
  - entity: ''
object_groups:
  - object_group: ''
name: Easy
objfile: easy.obj
mtlfile: easy.mtl
path: /config/www/Floor/`

Log from the console:
`floor3d-card.js?hacstag=361776538115:1086 THREE.OBJLoader: Unexpected line: "<!DOCTYPE html><html><head><link rel="modulepreload" href="/frontend_latest/core.2fe29b5a.js" crossorigin="use-credentials"><link rel="modulepreload" href="/frontend_latest/app.a6e743b8.js" crossorigin="use-credentials"><meta charset="utf-8"><link rel="manifest" href="/manifest.json" crossorigin="use-credentials"><link rel="icon" href="/static/icons/favicon.ico"><meta name="viewport" content="width=device-width,user-scalable=no,viewport-fit=cover"><style>body{font-family:Roboto,sans-serif;-moz-osx-font-smoothing:grayscale;-webkit-font-smoothing:antialiased;font-weight:400;margin:0;padding:0;height:100%}</style><title>Home Assistant</title><link rel="mask-icon" href="/static/icons/mask-icon.svg" color="#03a9f4"><link rel="apple-touch-icon" sizes="180x180" href="/static/icons/favicon-apple-180x180.png"><meta name="apple-itunes-app" content="app-id=1099568401"><meta name="apple-mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-status-bar-style" content="default"><meta name="apple-mobile-web-app-title" content="Home Assistant"><meta name="msapplication-square70x70logo" content="/static/icons/tile-win-70x70.png"><meta name="msapplication-square150x150logo" content="/static/icons/tile-win-150x150.png"><meta name="msapplication-wide310x150logo" content="/static/icons/tile-win-310x150.png"><meta name="msapplication-square310x310logo" content="/static/icons/tile-win-310x310.png"><meta name="msapplication-TileColor" content="#03a9f4ff"><meta name="mobile-web-app-capable" content="yes"><meta name="referrer" content="same-origin"><meta name="theme-color" content="#03A9F4"><meta name="color-scheme" content="dark light"><style>#ha-init-skeleton::before{display:block;content:"";height:56px;background-color:#03A9F4}html{background-color:var(--primary-background-color)}@media (prefers-color-scheme:dark){html{background-color:#111;color:#e1e1e1}#ha-init-skeleton::before{background-color:#1c1c1c}}</style></head><body><div id="ha-init-skeleton"></div><home-assistant></home-assistant><script>function _ls(e){var t=document.documentElement,i=t.insertBefore(document.createElement("script"),t.lastChild);return i.defer=!0,i.src=e,i}window.Polymer={lazyRegister:!0,useNativeCSSProperties:!0,dom:"shadow",suppressTemplateNotifications:!0,suppressBindingNotifications:!0},window.polymerSkipLoadingFontRoboto=!0,"customElements"in window&&"content"in document.createElement("template")||document.write("<script src='/static/polyfills/webcomponents-bundle.js'><\/script>");var isS11_12=/(?:.*(?:iPhone|iPad).*OS (?:11|12)_\d)|(?:.*Version\/(?:11|12)(?:\.\d+)*.*Safari\/)/.test(navigator.userAgent)</script><script>function _pf(o,t){var n=document.createElement("link");n.rel="preload",n.as="font",n.type="font/woff2",n.href=o,n.crossOrigin="anonymous",document.head.appendChild(n)}-1===navigator.userAgent.indexOf("Android")&&-1===navigator.userAgent.indexOf("CrOS")&&(_pf("/static/fonts/roboto/Roboto-Regular.woff2"),_pf("/static/fonts/roboto/Roboto-Medium.woff2"))</script><script crossorigin="use-credentials">isS11_12||(import("/frontend_latest/core.2fe29b5a.js"),import("/frontend_latest/app.a6e743b8.js"),window.customPanelJS="/frontend_latest/custom-panel.e5984c31.js",window.latestJS=!0,window.globalThis||(window.globalThis=window))</script><script>import("/hacsfiles/iconset.js");"
parse @ floor3d-card.js?hacstag=361776538115:1086
(anonymous) @ floor3d-card.js?hacstag=361776538115:1086
(anonymous) @ floor3d-card.js?hacstag=361776538115:1086
load (async)
load @ floor3d-card.js?hacstag=361776538115:1086
load @ floor3d-card.js?hacstag=361776538115:1086
_onLoaded3DMaterials @ floor3d-card.js?hacstag=361776538115:1086
(anonymous) @ floor3d-card.js?hacstag=361776538115:1086
(anonymous) @ floor3d-card.js?hacstag=361776538115:1086
load (async)
load @ floor3d-card.js?hacstag=361776538115:1086
load @ floor3d-card.js?hacstag=361776538115:1086
display3dmodel @ floor3d-card.js?hacstag=361776538115:1086
rerender @ floor3d-card.js?hacstag=361776538115:1086
_config_changed @ floor3d-card.js?hacstag=361776538115:59
handleEvent @ floor3d-card.js?hacstag=361776538115:31
floor3d-card.js?hacstag=361776538115:1086 THREE.OBJLoader: Unexpected line: "import("/browser_mod.js");"
parse @ floor3d-card.js?hacstag=361776538115:1086
(anonymous) @ floor3d-card.js?hacstag=361776538115:1086
(anonymous) @ floor3d-card.js?hacstag=361776538115:1086
load (async)
load @ floor3d-card.js?hacstag=361776538115:1086
load @ floor3d-card.js?hacstag=361776538115:1086
_onLoaded3DMaterials @ floor3d-card.js?hacstag=361776538115:1086
(anonymous) @ floor3d-card.js?hacstag=361776538115:1086
(anonymous) @ floor3d-card.js?hacstag=361776538115:1086
load (async)
load @ floor3d-card.js?hacstag=361776538115:1086
load @ floor3d-card.js?hacstag=361776538115:1086
display3dmodel @ floor3d-card.js?hacstag=361776538115:1086
rerender @ floor3d-card.js?hacstag=361776538115:1086
_config_changed @ floor3d-card.js?hacstag=361776538115:59
handleEvent @ floor3d-card.js?hacstag=361776538115:31
floor3d-card.js?hacstag=361776538115:1086 THREE.OBJLoader: Unexpected line: "</script><script>window.latestJS||(window.customPanelJS="/frontend_es5/custom-panel.11b503da.js",_ls("/frontend_es5/core.2615421e.js"),_ls("/frontend_es5/app.de916bd1.js"))</script><script>if (!window.latestJS) {"
parse @ floor3d-card.js?hacstag=361776538115:1086
(anonymous) @ floor3d-card.js?hacstag=361776538115:1086
(anonymous) @ floor3d-card.js?hacstag=361776538115:1086
load (async)
load @ floor3d-card.js?hacstag=361776538115:1086
load @ floor3d-card.js?hacstag=361776538115:1086
_onLoaded3DMaterials @ floor3d-card.js?hacstag=361776538115:1086
(anonymous) @ floor3d-card.js?hacstag=361776538115:1086
(anonymous) @ floor3d-card.js?hacstag=361776538115:1086
load (async)
load @ floor3d-card.js?hacstag=361776538115:1086
load @ floor3d-card.js?hacstag=361776538115:1086
display3dmodel @ floor3d-card.js?hacstag=361776538115:1086
rerender @ floor3d-card.js?hacstag=361776538115:1086
_config_changed @ floor3d-card.js?hacstag=361776538115:59
handleEvent @ floor3d-card.js?hacstag=361776538115:31
floor3d-card.js?hacstag=361776538115:1086 THREE.OBJLoader: Unexpected line: `"}</script></body></html>"``
