### ISSUE TITLE
Lock camera view?

### ISSUE THREAD

**Issue by wishie** [adizanni/floor3d-card#66]
Is it possible to lock the camera view so it can not be rotated or zoomed? I would love for this to be an option.

**Comment by adizanni** [comment]
Hello, this should not be difficult. I will put it in next release.

**Comment by wishie** [comment]
> Hello, this should not be difficult. I will put it in next release.

Thanks.

**Comment by adizanni** [comment]
I will release it in 1.1.7 (soon)

**Comment by adizanni** [comment]
lock_camera parameter added in release 1.1.10
