### ISSUE TITLE
Gesture for phone users

### ISSUE THREAD

**Issue by apprentice10** [adizanni/floor3d-card#67]
Hello!
I hope I'm not too late since I saw a post about locking the camera.
My proposition is to define the camera rotation, movement and actions for phone users and windows PC.
-Camera movement with middle button for windows and two fingers for phone.
-Camera rotation with CTRL+ middle button for windows and two fingers for phone.
(The middle button and/or two fingers is to not trigger any gesture)
-add 2 types of gestures click and hold. I'm not sure if this can be implemented but holding can open another card for more control (like for example the TV or boiler).
-As a Christmas bonus a dynamic label that can be assigned to a sensor (temperature for example)

I know is a lot and I have no idea if it's possible. But I really love this card.
Thank you and happy holidays!

**Comment by adizanni** [comment]
What you propose is feasible but either I define these gestures as configuration (complex) or I risk that other users prefer the current gesture. 
I'm not sure that I understand the dynamic label, but have you tried the text entity type ? It is always visible but it shows temperatures (and other texts) dynamically.

**Comment by adizanni** [comment]
Closing but keep it in the back-log for 1.2
