### ISSUE TITLE
[Feature Request] Adding text overlays for sensor information

### ISSUE THREAD

**Issue by wishie** [adizanni/floor3d-card#68]
I would like to be able to overlay some sensor information on top of the model (in the headspace on the outside of the 3d model)

I have attached a screenshot of my 3D model in Home Assistant, and circled a rough example of what I would like to be able to do (if possible).

Edit: Adding switches would be even cooler!

![feature-request](https://user-images.githubusercontent.com/635844/144698464-7aacbfb6-86eb-41a2-b87d-393ab0b4e624.jpg)

**Comment by adizanni** [comment]
Waiting for more sophisticated behaviour, I've implemented the more-info dialog on click. I know it is not the same (it is not on mouseover), but it is better than nothing.

**Comment by wishie** [comment]
How can I disable the more-info dialog? It has stopped my 'double click' gesture for turning on the lights from working

**Comment by adizanni** [comment]
Sorry wishie, you are right, I've not tested enough, the click is shadowing the dblclick. In the new version I'm releasing I've put a patch introducing the more_info parameter (no by default) of course all this requires a little more thinking....

**Comment by adizanni** [comment]
Wishie I have done a few changes in the management of click and overalys (still the current behavior should not be affected). This is the last version of additional things I can do based on your feedbacks. Please test and let me know

**Comment by wishie** [comment]
Im just trying the latest version now.. can you give an example of how 'overlay' is to be used?

**Comment by adizanni** [comment]
You first put overlay yes in the Appearance section of the card visual editor. Then a few other Overlay parameters appear to customize the overlay: alignment, size, fonts, colors, etc.
All this will create a panel that will sit on top of the model canvas.
You will also have to put the click parameter to yes for it to work.
Then in each entity you have the action parameter; this tells what to do when you click on the object associated to the entity.
If action = overlay for an entity, it means that when you click on it, it will display the name and state of the entity inside the overlay.

Ex
```yaml
........
overlay: 'yes'
overlay_bgcolor: transparent
.........
click: 'yes'
entities:
  - entity: <your_entity>
    object_id: <your_object_id>
    action: overlay
    .........
```

When you click on the object, the entity name and state will appear in the overlay panel

**Comment by wishie** [comment]
I gave it a quick test, but couldnt get any information to show in the overlay.. i will give it another go in the morning. Thanks for the work so far.

**Comment by adizanni** [comment]
Please @wishie , paste your config in the comments

**Comment by adizanni** [comment]
Result using vertical stack-in card:

![image](https://user-images.githubusercontent.com/35622920/151653815-a9f7624a-7e09-4691-afbd-7d088c6ac27d.png)

**Comment by adizanni** [comment]
in v1.1.15 the overlay text will change when the entity associated to it change the state. I consider this as fully implemented please answer

**Comment by adizanni** [comment]
I close as there is no further feedback
