### ISSUE TITLE
Feature-Request: Multiple floors, floors selectable by checkboxes

### ISSUE THREAD

**Issue by marrobHD** [adizanni/floor3d-card#69]
**Is your feature request related to a problem? Please describe.**
It would be cool if one card supports multiple floors selectable by checkboxes.

**Describe the solution you'd like**
Add Multiple floors, floors selectable by checkboxes

**Describe alternatives you've considered**
Creating own card for every floor

**Additional context**

**Comment by adizanni** [comment]
The Three.js library does not support this feature, what I can propose is to add the possibility to split the model I export using the plugin (https://github.com/adizanni/ExportToHASS) into one zip file for each floor giving you the possibility to have only one model but 1 card for each floor. Even then this would take a significant amount of time.
