### ISSUE TITLE
Different camera rotation between code and 3D view

### ISSUE THREAD

**Issue by Floyer007** [adizanni/floor3d-card#70]
**Checklist:**

- [x] I cleared the cache of my browser
- [x] I updated to the latest version available

**Release with the issue:** 1.1.5

**Last working release (if known):** New user today

**Browser and Operating System:** Firefox 95.0.1, Linux Mint 20.2 64Bit

**Description of problem:**

After getting the camera position and rotation from the 3D view by double clicking into white space, I got the coordinates like explained within the documentation.
The current selected view is one room of my flat in top-down perspective.
camera_position: { x: 142.39197663706742, y: 372.95204242685895, z: -511.3383214420605 }
camera_rotate: { x: -1.5472489731553267, y: 0.4442461998816112, z: 1.5160512996981885 }

After adding the coordinates into the card config and saving it, the camera doesn't look in the previous perspective anymore.
The camera is nearly rotated 90° up and 90° to the left.

If I get the new position now, the following coordinates are shown:
camera_position: { x: 142.39197663706753, y: 372.95204242685895, z: -511.33832144206036 }
camera_rotate: { x: -2.511429565824015, y: 0.22129923242939392, z: 2.9828461394081165 }

If I set this new rotation, the view stays the same now.

The whole map has 0,0 coordinate to the top left as mentioned in the docs.

**Comment by adizanni** [comment]
Hello I'm going to verify if I can reproduce and fix

**Comment by adizanni** [comment]
I can reproduce the problem but it I'm unable to fix. It has been introduced since the implementation of a few card size and position adjustments.

**Comment by Floyer007** [comment]
Thank you for investigating.
Is there a possible workaround?

**Comment by adizanni** [comment]
Have you tried to double click on an empty space when you have the model in the editor ? I have also some trouble but I have very slight differences between the captured position/rotation and the one that is displayed; also when doing the operation in with the Editor open the result is even more accurate

**Comment by adizanni** [comment]
If ti still does not work, please send me your model sh3d and/or obj

**Comment by Floyer007** [comment]
Yes, I used the empty space for the camera position within the editor.
Doesn't seem to help though. I still got the described rotation.
I have to note, that my previous information was for a room in the right bottom corner zoomed in.

As I figured out now, the camera always points in direction of the center of the model after leaving the editor.
This is true for all four edges.

If I use the top down from the middle of the model, the camera behaves normal.

**Comment by adizanni** [comment]
@Floyer007, please have a look to the last version 1.1.13. I think that I have improved the management of position and rotation save. Nevertheless there are still some remaining issues. Related to the card position.

**Comment by adizanni** [comment]
I close for lack of feedback, if the problem persist, please repost it

**Comment by Floyer007** [comment]
Yes, still persists within v1.1.13.
Will recheck it with another floorplan within the next weeks and will provide feedback if needed.
