### ISSUE TITLE
Lock movement of camera as well

### ISSUE THREAD

**Issue by Floyer007** [adizanni/floor3d-card#71]
Thank you for the camera lock feature since v1.1.10.
Appreciate your work!

Is it possible to add a second function to lock the camera translation/movement as well?

**Comment by adizanni** [comment]
Hey Floyer, you are right in the next version I will completely freeze the controls of the camera. Coming soon...

**Comment by Umarkhabiliy** [comment]
Hello Mr.Andy  I added js file  and after that i tried created 3d model, when i press refresh  button it is not rendering 3d view

**Comment by Umarkhabiliy** [comment]
Hello Mr.Andy  I added js file  and after that i tried created 3d model, when i press refresh  button it is not rendering 3d view

**Comment by adizanni** [comment]
Hello @Umarkhabiliy, please open a new issue, instead of commenting in a issue that is off topic. I need more info to help you. Screenshots, config, the model files, the error in the browser console. One of the most common source of errors is that the path of the model file is not the correct one.

**Comment by adizanni** [comment]
@Floyer007 last version 1.1.13 will do a final implementation of your request (full freeze)

**Comment by Floyer007** [comment]
Great!
So one for all rotations and one for movement?

Just locking rotation and unlock movement will be a scenario for top down view of large buildings an still navigate in them.

**Comment by adizanni** [comment]
No I've done only lock camera. For lock rotation zoom and movement separately I have to do another type of coding

**Comment by adizanni** [comment]
Please accept the current approach. I have to rethink the way to address your second requirement

**Comment by Floyer007** [comment]
Alright, I will look at it as well.
