### ISSUE TITLE
Panel mode doesn't fill the panel anymore

### ISSUE THREAD

**Issue by eldotta** [adizanni/floor3d-card#73]
**Checklist:**

- [ x ] I updated to the latest version available
- [ x ] I cleared the cache of my browser

**Release with the issue:**
v1.1.8 - v1.1.12

**Last working release (if known):**

not sure - tested all available releases via HACS down to v1.1.8 but no luck

**Browser and Operating System:**

Firefox on Win10, Home Assistant Companion App on iOS (iPhone)

**Description of problem:**

With updating to the latest release, display behaviour in panel mode changed and the card doesn't fill the whole pageanymore. This is especially annoying on mobile devices.

**Additional information:**

Screenshot from iPhone with Home Assistant Companion App. Prior to update the floorplan filled the whole screen. 

![grafik](https://user-images.githubusercontent.com/15805516/148840524-5b772fd9-882f-4319-88ab-8e7122f0d417.png)

BTW: GREAT WORK! 👍

**Comment by adizanni** [comment]
Hello @eldotta do you have a camera position and rotation saved in your card ? If yes can I ask you to remove it and recreate again (of course try to save somewhere the old values). I cannot reproduce it but in the last release I worked on the accuracy of the postion and rotation of the camera and I may have borken something.

**Comment by eldotta** [comment]
Thanks for the quick feedback! I do have, will check tomorrow and get back to you…
>

**Comment by adizanni** [comment]
I confirm the problem is introduced with 1.1.12. I will try to fix rapidly

**Comment by adizanni** [comment]
v1.1.13 is out, please test and advise if the issue can be closed. Sorry for the uncovenience, it is more and more difficult to do proper testing

**Comment by eldotta** [comment]
Yepp, works again. Many thanks!!

No need to be sorry, thank you four your work on behalf of the whole
community! :)

Am Di., 11. Jan. 2022 um 20:01 Uhr schrieb andy1970 <
***@***.***>:
