### ISSUE TITLE
object_groups do not show in the drop down list of the object_id

### ISSUE THREAD

**Issue by uspass** [adizanni/floor3d-card#77]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
any
**Last working release (if known):**
none
**Browser and Operating System:**
any browser on Windows 10

**Description of problem:**

When one defines an entity in Lovelace UI edit mode, in the drop down list of the object_id, object_groups do not show. Only individual object_ids appear in the list. To overcome this, one has to manually do "Edit Dashboard"-> "Raw configuration editor" and write the object_group name.

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by adizanni** [comment]
Ok acknowledged

**Comment by adizanni** [comment]
I've corrected it in v1.1.15 please verify.

**Comment by uspass** [comment]
It looks great.
Thanks!
