### ISSUE TITLE
Directional Light support

### ISSUE THREAD

**Issue by jeremyoha450** [adizanni/floor3d-card#78]
Love this. i have one issue regarding your card. is there a way to stop the light going through walls without enabling shadow?

if not. can you add this feature be added to the card? as i have alot of lights on my plan around the outside of the house and they are going through the walls

**Comment by adizanni** [comment]
Hello @jeremyoha450, unfortunately I cannot change this. I have added the possibility to activate the shadow for the full card and then only activate shadow for some lights, but the shadow mechnaism is a very complex feature of the 3d library I'm using and I cannot change the behaviour. In a future release I can add directional lights that can be useful if your outdoor lights are pointing outward: thanks to this you may not need to activate the shadow for them.

**Comment by jeremyoha450** [comment]
that would be a good idea. would help alot with not light overflowing into inside the house/rooms, etc

**Comment by adizanni** [comment]
I close this but I have added it to the 1.2 project enhancements
