### ISSUE TITLE
Help needed: How to do the floor3d full card like in the example videos?

### ISSUE THREAD

**Issue by marrobHD** [adizanni/floor3d-card#8]
Help needed: How to do the floor3d full card like in the example videos?
The card is quite small.

![xHJFoUmNjG](https://user-images.githubusercontent.com/29308361/122528869-1632f780-d01d-11eb-94df-63e1e0d386de.jpg)

**Comment by adizanni** [comment]
Hello marrobHD, you need to create a view in Panel mode (it is a switch you need to turn on when creating the view). You can also put a style attribute in the card, this way:

````
style: 'height: 700px; width: 700px'
````

**Comment by adizanni** [comment]
Hope  I answered in my comment before

**Comment by marrobHD** [comment]
yep you did. I forgot to reply. 
Thanks!
