### ISSUE TITLE
How to deal with 2 floor house?

### ISSUE THREAD

**Issue by Travis-Prall** [adizanni/floor3d-card#80]
**Is your feature request related to a problem? Please describe.**
I have a two story house, I know one way would be to create two floorpan ,but I already created a full house. Would there be a best way to show and hide the entire second floor?

**Describe the solution you'd like**
Button that is able to show or hide a entire floor.

**Comment by adizanni** [comment]
@Travis-Prall, yes I can think of it in a future release a tab. In the meantime as you are saying it is not that complex to split the 2 floors into 2 separate models. And you may use a custom card like this one (https://community.home-assistant.io/t/lovelace-swiper-card/72447?u=frenck )to swipe between the 2 floors

**Comment by Travis-Prall** [comment]
Actually nevermind, I found out you can click on the level in sweethome3d and click show only this level. Then you can click export to export only that level.

**Comment by adizanni** [comment]
Yes deal with levels is quite simple in Sweethome3d; I did not know that you could export only one level though. Do you allow me to close this issue ?
