### ISSUE TITLE
Bug with cover entitiy?

### ISSUE THREAD

**Issue by H4rl3k1n** [adizanni/floor3d-card#82]
Hey,

I tryed the new cover function, it works perfectly with a window cover. I discovered a visual bug/problem with my door covers.
As you can see in my sweet home 3d model the cover covers (?) the full door:
![rolo plan](https://user-images.githubusercontent.com/63719436/154793928-55c886a8-1177-417d-8628-9db27af791f1.png)

By using the cover entitiy theres a gap on top, this picture shows cover with 66% (gap is allways there, from 1-100%).

![rolo live](https://user-images.githubusercontent.com/63719436/154794042-0fa99ece-f076-4a80-aa40-662d3cba93de.png)

**Comment by adizanni** [comment]
Hello @H4rl3k1n, would you mind to send me your model or  the type of furniture you are using in Sweethome3d, and your config

**Comment by H4rl3k1n** [comment]
sure, no problem:

`          - entity: cover.shellyrdgb1
            type3d: cover
            object_id: sweethome3d_opening_on_rail_1_Roller_Shutter_Foot_back_119_6_529
            cover:
              pane: sweethome3d_opening_on_rail_1_Roller_Shutter_Foot_back_119_6_529
              side: up`

i guess "sweethome3d_opening_on_rail_1_Roller_Shutter_Foot_back" is the model in sweet home 3d?

**Comment by H4rl3k1n** [comment]
i think i found it. I used a window-cover with a new size for my doors, if i use a covered door it works perfectly.
Need to replace the objects in sweet home 3d. Think you can close it. Thanks anyway.

**Comment by adizanni** [comment]
It is supposed to work also for a resized window but if you have fixed, we can close this and see if others have similar issues
