### ISSUE TITLE
LEVEL BUTTONS COLOR

### ISSUE THREAD

**Issue by VITCHEPF** [adizanni/floor3d-card#85]
**Is your feature request related to a problem? Please describe.**

The best background color to highlight the 3D model is the black color, however when we use this color the level buttons (Left - Top) are not visible.

**Describe the solution you'd like**

I suggest creating a configuration option on the card to change the color of the buttons as we wish "Level_Buttons_Collor: "

**Describe alternatives you've considered**

Allow at least 3 colors for the buttons - White or Black or Gray.

SEE PICTURE BELOW:

![BACKGROUND_COLOR](https://user-images.githubusercontent.com/73760504/156423359-98afb78b-b64d-4572-aab5-5227a41a684a.jpg)

**Comment by adizanni** [comment]
Yes, acknowledged. I will do a quick and dirty patch with a background for the level icons. In a future release the levels will become toggle box so that we can show the levels we want....

**Comment by VITCHEPF** [comment]
Issue solved in revision 1.3.3


![CASA](https://user-images.githubusercontent.com/73760504/156762765-ad62535e-9192-4dcf-9e6b-c0fbef76ae59.jpg)
