### ISSUE TITLE
Object black after update to 1.3.X

### ISSUE THREAD

**Issue by aschobba** [adizanni/floor3d-card#87]
After updating to any 1.3.X my object turns to black.

![image](https://user-images.githubusercontent.com/5717166/156608790-1fbe8aaf-e95d-4496-b5d0-1e59aa50aa0a.png)

**Comment by VITCHEPF** [comment]
Hi, try this:
1) Set the GLOBAL SCENE LIGHTS  parameter with value (1) to view the image with color;
2) Browser cache should be cleared after loading a new object or 
3) Add a version tag to the name of the obj and mtl files. Ex: home.obj?ver=1 and increase the number for any new version of the model

**Comment by aschobba** [comment]
Setting GLOBAL SCENE LIGHTS to 1 fixed the issue

**Comment by adizanni** [comment]
Ok good and thanks @VITCHEPF

**Comment by drageloth** [comment]
I also had to do that one for the object to load. In my case it was total black. Maybe it's needed to put it on the how-to as a workaround?

**Comment by aschobba** [comment]
Just install the latest update.
There is Global Scene lights back to 0.2 by default.
