### ISSUE TITLE
Associate multiple objects to one Home Assistant Entity

### ISSUE THREAD

**Issue by jjmuriel** [adizanni/floor3d-card#9]
Hi,
It's possible to allow the association of multiple objects to one Home Assistant entity? Thanks

**Comment by adizanni** [comment]
Yes it is possible and I understantd the use case, but it is not a small one. Need to see how to implement it

**Comment by jjmuriel** [comment]
Thank you @adizanni . I'm very happy with your custom card and think that have a lot of potential.

**Comment by adizanni** [comment]
Managed by feature request: https://github.com/adizanni/floor3d-card/issues/11

**Comment by jjmuriel** [comment]
Thank you @adizanni .
