### ISSUE TITLE
Larger area for light clicks

### ISSUE THREAD

**Issue by dtjohnson90** [adizanni/floor3d-card#93]
**Checklist:**

- [ x ] I updated to the latest version available
- [ x ] I cleared the cache of my browser

**Release with the issue:**
Latest
**Last working release (if known):**
NA
**Browser and Operating System:**
macOS 12.2 - Safari

**Description of problem:**
Is there any way to create a large area in order to turn the light in a room on / off? For instance, most of the lights in SweetHome3D are relatively small and getting an exact click with a mouse can be tough. An example would be clicking roughly the middle of the room to make it work. 

Things I have tried:
- Creating a hidden box in the middle of the room, however the object is not exported
- Creating a box in the middle of the room with a transparent png texture, however the box now shows up as a black square in Home Assistant

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

<img width="492" alt="Screen Shot 2022-04-01 at 8 31 04 PM" src="https://user-images.githubusercontent.com/5649115/161360292-dc0f81b6-7a42-4eae-9c23-e942d2dafd07.png">

**Comment by dtjohnson90** [comment]
So I may have found a little workaround. I created two entity's for the same light. One was a tiny square object on the ceiling and the other is the room itself. I set the lumens of the room light to 0, so that the only light showing is from the ceiling. 

With that setup, I can click anywhere on the floor in the room to turn on the light. Not sure if this is the best option, but at least it works! 

`
- entity: light.office_light
            action: default
            type3d: light
            object_id: Office_Light_2
            light:
              lumens: '2000'
              decay: '1'
              distance: '300'
              shadow: 'yes'
              vertical_alignment: top
          - entity: light.office_light
            action: default
            type3d: light
            object_id: room_4_1
            light:
              lumens: '0'
              color: white
              decay: '2'
              distance: '0'
              shadow: 'no'
`

**Comment by adizanni** [comment]
Hello @dtjohnson90, you also have the gesture entity that can do the same as what you have done but consuming one less light (you know that the number of light is limited).

an example of gesture for your office light can be:

```yaml
  -  entity: light.office_light
     type3d: gesture
     object_id: room_4_1
     gesture:
        domain: light
        service: toggle
```

**Comment by dtjohnson90** [comment]
That's exactly what I was looking for! Thank you!
