### ISSUE TITLE
Problem v after updating

### ISSUE THREAD

**Issue by niro-zz** [adizanni/floor3d-card#94]
Hi
In version 1.3.9 everything worked fine with no problems 

After I updated version to 1.3.10 there were issues
All the functions of the objects within the model no longer work but "levels" work
It also did not work on the cell phone in the "Note 10"
In version 1.4.0 I saw that adding a new "zoom" function it also works for me but all the other things do not

Thank you
It's just amazing your work

And sorry for my English hope you understand

**Comment by adizanni** [comment]
Hello @niro-zz, it is not normal I have not touched other entities and my tests have not revealed any issue. Can you give more info: config, models, etc. ?

**Comment by niro-zz** [comment]
I know it's really weird But I tried every possible way I deleted everything I reinstalled I cleaned up the Chrome browser In general if my settings work In version 1.3.9 It should also work in version 1.4.0 right? I will check myself again and update

**Comment by adizanni** [comment]
You can always revert back to 1.3.9 if you have problems. You can ask HACS to force the redownload of a previous version

**Comment by niro-zz** [comment]
Hi I have updated to version 1.4.2hf2 The default model works for me I'm starting to realize there's a problem with my 3D model When I load the model the double click option disappears To view the information of the camera and also the information of the objects What is better? glb file or obj When I load glb it's not wrong obj it's ok I created the glb file With the tool you posted in the same cast that this option came out What is the best way to create the 3d model? And thanks again

**Comment by adizanni** [comment]
@niro-zz, I think that the obj format is still the best because it is created directly by Sweethome3d, in terms of fidelity of the rendering I did not find better. Glb has still some side effect related to the management of coordinates and the brightness of the objects. I recommend the glb format only when the models are big. Glb allows to cut the load time by half and sometimes more (this depends on the number of texture), the more the texture, the less will be the performance gain of glb. Of course I'm working to make glb become the primary format, but in order to achieve that, I need the plugin ExportToHass to include the glb export feature

**Comment by adizanni** [comment]
@niro-zz, related to the double-click, when you are in Edit mode (either in full screen or in the editor) the double-click is showing the name of the object or the camera settings depending on where you click. In non-editing mode, the double-click is used to trigger the actions: turn on the lights, trigger the service in the gesture entities, etc.

**Comment by niro-zz** [comment]
I think I have the problem with the model In something related to "scenes" If I upload the obj file it works fine In short it seems to me I also have a lot of file problems I'm working on everything again And updated Thank you Thank you Thank you

**Comment by adizanni** [comment]
Please @niro-zz  can you update on this issue ?

**Comment by niro-zz** [comment]
Hey
 Apparently there is a problem maybe from my file I had an older file with no levels And it works I left everything right now because my computer is a little weak for 3D I want to buy a new computer in the near future and create a new file "3d model" Update when this happens Thanks

**Comment by adizanni** [comment]
@xfyisheng, I need more info, at least the configuration of the card and after, if needed, the model files.

**Comment by adizanni** [comment]
@xfyisheng, please can you update this issue ?

**Comment by wenxu502** [comment]
> 记录器：前端.js.latest.202204050 来源：组件/system_log/**初始化**.py：190 首次出现：23：16：56（11 次出现） 上次记录时间：http://192.168.2.2:8123/local/floor3d-card.js?ver=14555:2262:31468 未捕获[错误 23](http://192.168.2.2:8123/local/floor3d-card.js?ver=14555:2262:31468)：20：52

I encountered the same problem, which was solved by deleting the entity in the default configuration

**Comment by adizanni** [comment]
Yes, I've put a comment in the community forum. In next release I will try to better manage the error related to inexistent entity. Now I keep the issue open as a placeholder for fixing.
