### ISSUE TITLE
Roller/Cover/Shutters support

### ISSUE THREAD

**Issue by diamant-x** [adizanni/floor3d-card#97]
Hi,

Thanks for all the effort to make this card possible and such 'easy' to get started with from a SH3D model.
I'm trying to get started with the cover/roller support, however i'm unable to make it work. 

- Could you share which SweetHome3D model/object you used for the example in your Readme? I'm sharing mine below.
- Could you share the yaml code used for the same example, and the objectID definition used?

In particular, I set up all the needed parameters, and:

-  as long as i don't add the pane element, the model loads but the roller doesn't change its position/visibility. I confirm my 'cover' entity has a 'current_position' attribute, which seems to be mandatory based on your source code.
- If I add the pane element then the model doesn't load at all (black screen), with below console error.

```
styles.ts:368 
        
       Uncaught (in promise) TypeError: n.toArray is not a function
    at ns (floor3d-card.js?hacstag=3617765381412:2205:258462)
    at Vs.Cs [as setValue] (floor3d-card.js?hacstag=3617765381412:2205:261674)
    at Function.Ys.upload (floor3d-card.js?hacstag=3617765381412:2205:265074)
    at Tt (floor3d-card.js?hacstag=3617765381412:2205:354713)
    at Ha.renderBufferDirect (floor3d-card.js?hacstag=3617765381412:2205:346480)
    at y (floor3d-card.js?hacstag=3617765381412:2205:298182)
    at y (floor3d-card.js?hacstag=3617765381412:2205:298271)
    at y (floor3d-card.js?hacstag=3617765381412:2205:298271)
    at y (floor3d-card.js?hacstag=3617765381412:2205:298271)
    at Ra.render (floor3d-card.js?hacstag=3617765381412:2205:299668)
```

This is the SH3D model i'm using as roller, which is freely available in their website: https://www.sweethome3d.com/models/katorlegaz/window-blinds.zip https://www.sweethome3d.com/freeModels.jsp
![image](https://user-images.githubusercontent.com/7346338/163154415-d6dcae21-37b4-49b4-a8fd-1ceede3decab.png)

Thanks!

**Comment by diamant-x** [comment]
Thanks. Yes i'm using your plugin and had renamed already the objects (using no spaces or dashes, i follow Camel naming pattern).
For your third point, i checked my obj file and i can't find any METAL material reference linked to the blinds; all of them are
`usemtl silver_window_blinds_1
`

**Comment by adizanni** [comment]
In this case it is possible you are not using the same library you sent me. Anyway if you define the object as in my config (using the object groups), it should work now. The only problem is that your top element will be cut-off because it is using the same material as the other moving elements. Just as a proof of what I'm saying you can duplicate the silver_window_blinds_1 in the mtl file (say silver_window_blinds_2) and than reference the new material from the object tagged _4 (the top blind drawer)

**Comment by adizanni** [comment]
;). Try the other one in a separate simple model. The one you sent me is a little messed up with the axis. The principle is in the object_id field of the entity, you put the group of things that need to move (blades and cords), in the pane you put the object whose top is the cutting plane to make the object disappear when lifted.
