### ISSUE TITLE
Add Entities

### ISSUE THREAD

**Issue by zzaal** [adizanni/floor3d-card#99]
Hello!
Perfect poject!
Why can't more than 16 entities be added?
After adding 16 entities does not allow you to select 17

**Comment by adizanni** [comment]
Hello @zzaal, it is not that you cannot select more entities it is that when you reach a certain number of entities, the editor becomes very heavy so I remove the combo box for the selection of the entity. You can still copy paste the name of the entity and you can create as many entities as you want.

Another limitation is that you cannot have more than X number of lights, where X is equal to the parameter "Max Texture Image Units" in the report you find a this address: https://webglreport.com/?v=2
But this is not enforced, at the X+1 light you define the card will behave wrongly.

**Comment by zzaal** [comment]
Ok. 
Thx.
